class Restaurant {
  int? id;
  String? createdAt;
  String? updatedAt;
  String? name;
  String? subdomain;
  String? logo;
  String? cover;
  String? active;
  int? userId;
  String? lat;
  String? lng;
  String? address;
  String? phone;
  String? minimum;
  String? description;
  int? fee;
  int? staticFee;
  List<Radiuss>? radius;
  int? isFeatured;
  int? cityId;
  int? views;
  int? canPickup;
  int? canDeliver;
  int? selfDeliver;
  int? freeDeliver;
  String? whatsappPhone;
  String? fbUsername;
  int? doCovertion;
  String? currency;
  String? paymentInfo;
  String? molliePaymentKey;
  String? alias;
  String? logom;
  String? icon;
  String? coverm;
  bool? isbookmarked;
  List<TimeSlot>? timeslotlist;
  String? openingTime;
  String? closingTime;
  String? rating;
  String? deliveryTime;
  String? blurUrl;
  String? localimg;

  Restaurant({
    this.id,
    this.openingTime,
    this.closingTime,
    this.createdAt,
    this.updatedAt,
    this.name,
    this.subdomain,
    this.logo,
    this.cover,
    this.active,
    this.userId,
    this.lat,
    this.lng,
    this.address,
    this.phone,
    this.minimum,
    this.description,
    this.fee,
    this.staticFee,
    this.radius,
    this.isFeatured,
    this.cityId,
    this.views,
    this.canPickup,
    this.canDeliver,
    this.selfDeliver,
    this.freeDeliver,
    this.whatsappPhone,
    this.fbUsername,
    this.doCovertion,
    this.currency,
    this.paymentInfo,
    this.molliePaymentKey,
    this.alias,
    this.logom,
    this.icon,
    this.coverm,
    this.isbookmarked,
    this.timeslotlist,
    this.rating,
    this.deliveryTime,
    this.blurUrl,
    this.localimg,
  });
}

class Radiuss {
  double? lat;
  double? lng;

  Radiuss({this.lat, this.lng});
}

class TimeSlot {
  String? id;
  String? title;

  TimeSlot({this.id, this.title});
}

List<TimeSlot> timeSlotlist = [
  TimeSlot(id: "1", title: "8:00AM-8:30AM"),
  TimeSlot(id: "2", title: "8:30AM-9:00AM"),
  TimeSlot(id: "3", title: "9:00AM-10:00AM"),
  TimeSlot(id: "4", title: "4:00PM-5:00PM"),
  TimeSlot(id: "5", title: "5:00PM-6:00PM"),
];

List<Restaurant> restaurantlist = [
  Restaurant(
      id: 1,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Bronx VanNest",
      subdomain: "Drinks",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_a.jpg?alt=media&token=19b668de-984a-4021-bd67-82d0e9bb6c6e",
      localimg: "assets/images/fullApps/foodMaster/homeimage_a.jpg",
      cover: "",
      active: "1",
      userId: 1,
      lat: "0",
      lng: "0",
      address: "6 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "1",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [Radiuss(lat: 40.2156451454, lng: -73.9118562)],
      isFeatured: 1,
      cityId: 1,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "123456789",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_a.jpg?alt=media&token=19b668de-984a-4021-bd67-82d0e9bb6c6e",
      icon: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      coverm: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      isbookmarked: true,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LKI|%dV@Eho#Y8nNe.NG9ZxYW=RO"),
  Restaurant(
      id: 2,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Morris Park Burger",
      subdomain: "lunch",
      localimg: "assets/images/fullApps/foodMaster/homeimage_c.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_c.jpg?alt=media&token=8e65ee67-1b80-4fac-a1f1-f2956d77e669",
      cover: "",
      active: "1",
      userId: 2,
      lat: "0",
      lng: "0",
      address: "8 Sardar nagar",
      phone: "7984765799",
      minimum: "2",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 1,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "523469871",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test1",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_c.jpg?alt=media&token=8e65ee67-1b80-4fac-a1f1-f2956d77e669",
      icon: "assets/images/fullApps/foodMaster/Vandal_Burgers.png",
      coverm: "assets/images/fullApps/foodMaster/Vandal_Burgers.png",
      isbookmarked: false,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "25 Min",
      blurUrl: "L5F#s.r#0001^+IVtL-;00^~~Ati"),
  Restaurant(
      id: 3,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "NorWood Burito",
      subdomain: "Dinner",
      localimg: "assets/images/fullApps/foodMaster/homeimage_b.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_b.jpg?alt=media&token=ee048a16-c970-47fc-9673-9f41f6beeac0",
      cover: "",
      active: "1",
      userId: 3,
      lat: "0",
      lng: "0",
      address: "9 Yukon Drive Raeford, NC 28376, NC 28376",
      phone: "7984765799",
      minimum: "1",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 1,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 0,
      whatsappPhone: "123578985",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_b.jpg?alt=media&token=ee048a16-c970-47fc-9673-9f41f6beeac0",
      icon: "assets/images/fullApps/foodMaster/NorWoodBurito.png",
      coverm: "assets/images/fullApps/foodMaster/NorWoodBurito.png",
      isbookmarked: true,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "55 Min",
      blurUrl: "LJF5ma-.R,xv%1~V={T0IUrq%1xu"),
  Restaurant(
      id: 4,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Pizza Relham",
      subdomain: "Drinks",
      localimg: "assets/images/fullApps/foodMaster/homeimage_d.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_d.jpg?alt=media&token=8fb4aae5-3873-4297-b998-e67510db647f",
      cover: "",
      active: "1",
      userId: 4,
      lat: "0",
      lng: "0",
      address: "2 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "2",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 2,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "15647822568",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_d.jpg?alt=media&token=8fb4aae5-3873-4297-b998-e67510db647f",
      icon: "assets/images/fullApps/foodMaster/Pizza_Relhan.png",
      coverm: "assets/images/fullApps/foodMaster/Pizza_Relhan.png",
      isbookmarked: false,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "15 Min",
      blurUrl: "LFJ%OJD*K5Vr00-Un\$oy?^-VR6sn"),
  Restaurant(
      id: 5,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Malibu Diner",
      subdomain: "Dinner",
      logo: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      cover: "",
      active: "1",
      userId: 5,
      lat: "0",
      lng: "0",
      address: "3 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "1",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 2,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 0,
      whatsappPhone: "12546682525",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      localimg: "assets/images/fullApps/foodMaster/homeimage_e.jpg",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_e.jpg?alt=media&token=a0ff5342-2e1d-472d-ae04-559fcc6a4f34",
      icon: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      coverm: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      isbookmarked: true,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "35 Min",
      blurUrl: "LHJ7aL9qKQWE_KI,E1s=Sks+ITXS"),
  Restaurant(
      id: 6,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Vandal Burgers",
      subdomain: "Drinks",
      localimg: "assets/images/fullApps/foodMaster/homeimage_f.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_f.jpg?alt=media&token=6785c149-e2d7-4a74-a407-1bf78fcb623d",
      cover: "",
      active: "1",
      userId: 6,
      lat: "0",
      lng: "0",
      address: "5 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "2",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 3,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "1458574585585",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_f.jpg?alt=media&token=6785c149-e2d7-4a74-a407-1bf78fcb623d",
      icon: "assets/images/fullApps/foodMaster/Vandal_Burgers.png",
      coverm: "assets/images/fullApps/foodMaster/Vandal_Burgers.png",
      isbookmarked: true,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "65 Min",
      blurUrl: "LGF}=-~WtSRj?HM_s.M_XA%2%2NG"),
  Restaurant(
      id: 7,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "il Buco",
      subdomain: "lunch",
      localimg: "assets/images/fullApps/foodMaster/homeimage_g.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_g.jpg?alt=media&token=cdc629d4-40c1-4ac2-908d-d4cd4420c0b5",
      cover: "",
      active: "1",
      userId: 7,
      lat: "0",
      lng: "0",
      address: "2 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "3",
      description: "Drinks",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 3,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 0,
      whatsappPhone: "12354987",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_g.jpg?alt=media&token=cdc629d4-40c1-4ac2-908d-d4cd4420c0b5",
      icon: "assets/images/fullApps/foodMaster/NorWoodBurito.png",
      coverm: "assets/images/fullApps/foodMaster/NorWoodBurito.png",
      isbookmarked: false,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "15 Min",
      blurUrl: "LMD]J1#RDSVa~prXMzi}58M_yAXl"),
  Restaurant(
      id: 8,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Pizza Manhattn",
      subdomain: "Dinner",
      localimg: "assets/images/fullApps/foodMaster/homeimage_h.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_h.jpg?alt=media&token=62f2a2c0-a848-4178-8aa8-af2dea6d8fb3",
      cover: "",
      active: "1",
      userId: 8,
      lat: "0",
      lng: "0",
      address: "10 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "4",
      description: "Drinks, Lunch",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 4,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "1254884",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_h.jpg?alt=media&token=62f2a2c0-a848-4178-8aa8-af2dea6d8fb3",
      icon: "assets/images/fullApps/foodMaster/Pizza_Relhan.png",
      coverm: "assets/images/fullApps/foodMaster/Pizza_Relhan.png",
      isbookmarked: true,
      timeslotlist: [],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "20 Min",
      blurUrl: "LEG%_H}=02Rl4o-S^*xF2vo|IUEM"),
];

List<Restaurant> restaurantlist1 = [
  Restaurant(
      id: 1,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Bronx VanNest Restorant",
      subdomain: "Drinks",
      localimg: "assets/images/fullApps/foodMaster/homeimage_a.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_a.jpg?alt=media&token=19b668de-984a-4021-bd67-82d0e9bb6c6e",
      cover: "",
      active: "1",
      userId: 1,
      lat: "0",
      lng: "0",
      address: "6 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "0",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [Radiuss(lat: 40.2156451454, lng: -73.9118562)],
      isFeatured: 1,
      cityId: 1,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 0,
      whatsappPhone: "123456789",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_a.jpg?alt=media&token=19b668de-984a-4021-bd67-82d0e9bb6c6e",
      icon: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      coverm: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      isbookmarked: true,
      timeslotlist: [TimeSlot(id: "1", title: "3pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LKI|%dV@Eho#Y8nNe.NG9ZxYW=RO"),
  Restaurant(
      id: 2,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Morris Park Burger",
      subdomain: "lunch",
      localimg: "assets/images/fullApps/foodMaster/homeimage_c.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_c.jpg?alt=media&token=8e65ee67-1b80-4fac-a1f1-f2956d77e669",
      cover: "",
      active: "1",
      userId: 2,
      lat: "0",
      lng: "0",
      address: "8 Sardar nagar",
      phone: "7984765799",
      minimum: "0",
      description: "Italian, Pasta",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 2,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "523469871",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test1",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_c.jpg?alt=media&token=8e65ee67-1b80-4fac-a1f1-f2956d77e669",
      icon: "assets/images/fullApps/foodMaster/Vandal_Burgers.png",
      coverm: "assets/images/fullApps/foodMaster/Vandal_Burgers.png",
      isbookmarked: false,
      timeslotlist: [TimeSlot(id: "2", title: "4pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "L5F#s.r#0001^+IVtL-;00^~~Ati"),
  Restaurant(
      id: 3,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "NorWood Burito",
      subdomain: "Dinner",
      localimg: "assets/images/fullApps/foodMaster/homeimage_b.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_b.jpg?alt=media&token=ee048a16-c970-47fc-9673-9f41f6beeac0",
      cover: "",
      active: "1",
      userId: 3,
      lat: "0",
      lng: "0",
      address: "9 Yukon Drive Raeford, NC 28376, NC 28376",
      phone: "7984765799",
      minimum: "0",
      description: "Drinks, Beef Burgers",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 3,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 0,
      whatsappPhone: "123578985",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_b.jpg?alt=media&token=ee048a16-c970-47fc-9673-9f41f6beeac0",
      icon: "assets/images/fullApps/foodMaster/NorWoodBurito.png",
      coverm: "aassets/images/fullApps/foodMaster/NorWoodBurito.png",
      isbookmarked: true,
      timeslotlist: [TimeSlot(id: "3", title: "3pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LJF5ma-.R,xv%1~V={T0IUrq%1xu"),
  Restaurant(
      id: 4,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Pizza Relham",
      subdomain: "Drinks",
      localimg: "assets/images/fullApps/foodMaster/homeimage_d.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_d.jpg?alt=media&token=8fb4aae5-3873-4297-b998-e67510db647f",
      cover: "",
      active: "1",
      userId: 4,
      lat: "0",
      lng: "0",
      address: "2 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "0",
      description: "Tacos, Wraps",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 4,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "15647822568",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_d.jpg?alt=media&token=8fb4aae5-3873-4297-b998-e67510db647f",
      icon: "assets/images/fullApps/foodMaster/Pizza_Relhan.png",
      coverm: "aassets/images/fullApps/foodMaster/Pizza_Relhan.png",
      isbookmarked: false,
      timeslotlist: [TimeSlot(id: "4", title: "4pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LFJ%OJD*K5Vr00-Un\$oy?^-VR6sn"),
  Restaurant(
      id: 5,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Malibu Diner",
      subdomain: "Dinner",
      localimg: "assets/images/fullApps/foodMaster/homeimage_e.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_e.jpg?alt=media&token=a0ff5342-2e1d-472d-ae04-559fcc6a4f34",
      cover: "",
      active: "1",
      userId: 5,
      lat: "0",
      lng: "0",
      address: "3 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "0",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 5,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 0,
      whatsappPhone: "12546682525",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_e.jpg?alt=media&token=a0ff5342-2e1d-472d-ae04-559fcc6a4f34",
      icon: "assets/images/fullApps/foodMaster/Malibu_Diner.png",
      coverm: "aassets/images/fullApps/foodMaster/Malibu_Diner.png",
      isbookmarked: true,
      timeslotlist: [TimeSlot(id: "5", title: "5pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LHJ7aL9qKQWE_KI,E1s=Sks+ITXS"),
  Restaurant(
      id: 6,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Vandal Burgers",
      subdomain: "Drinks",
      localimg: "assets/images/fullApps/foodMaster/homeimage_f.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_f.jpg?alt=media&token=6785c149-e2d7-4a74-a407-1bf78fcb623d",
      cover: "",
      active: "1",
      userId: 6,
      lat: "0",
      lng: "0",
      address: "5 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "0",
      description: "Drinks, Lunch, Bbq",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 6,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "1458574585585",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_f.jpg?alt=media&token=6785c149-e2d7-4a74-a407-1bf78fcb623d",
      icon: "assets/images/fullApps/foodMaster/Vandal_Burgers.png",
      coverm: "aassets/images/fullApps/foodMaster/Vandal_Burgers.png",
      isbookmarked: true,
      timeslotlist: [TimeSlot(id: "6", title: "6pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LGF}=-~WtSRj?HM_s.M_XA%2%2NG"),
  Restaurant(
      id: 7,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "il Buco",
      subdomain: "lunch",
      localimg: "assets/images/fullApps/foodMaster/homeimage_g.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_g.jpg?alt=media&token=cdc629d4-40c1-4ac2-908d-d4cd4420c0b5",
      cover: "",
      active: "1",
      userId: 7,
      lat: "0",
      lng: "0",
      address: "2 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "0",
      description: "Drinks",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 7,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 0,
      whatsappPhone: "12354987",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_g.jpg?alt=media&token=cdc629d4-40c1-4ac2-908d-d4cd4420c0b5",
      icon: "assets/images/fullApps/foodMaster/NorWoodBurito.png",
      coverm: "assets/images/fullApps/foodMaster/NorWoodBurito.png",
      isbookmarked: false,
      timeslotlist: [TimeSlot(id: "7", title: "7pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LMD]J1#RDSVa~prXMzi}58M_yAXl"),
  Restaurant(
      id: 8,
      createdAt: "2021-02-18T11:50:31.000000Z",
      updatedAt: "2021-02-26T12:17:24.000000Z",
      name: "Pizza Manhattn",
      subdomain: "Dinner",
      localimg: "assets/images/fullApps/foodMaster/homeimage_h.jpg",
      logo:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_h.jpg?alt=media&token=62f2a2c0-a848-4178-8aa8-af2dea6d8fb3",
      cover: "",
      active: "1",
      userId: 8,
      lat: "0",
      lng: "0",
      address: "10 Yukon Drive Raeford, NC 28376",
      phone: "7984765799",
      minimum: "0",
      description: "Italian, Pasta",
      fee: 0,
      staticFee: 0,
      radius: [],
      isFeatured: 1,
      cityId: 8,
      views: 5,
      canPickup: 1,
      canDeliver: 1,
      selfDeliver: 0,
      freeDeliver: 1,
      whatsappPhone: "1254884",
      fbUsername: null,
      doCovertion: 0,
      currency: "",
      paymentInfo: "",
      molliePaymentKey: "",
      rating: "0",
      alias: "test2",
      logom:
          "https://firebasestorage.googleapis.com/v0/b/smartkit-8e62c.appspot.com/o/foodmaster%2Fhomeimage_h.jpg?alt=media&token=62f2a2c0-a848-4178-8aa8-af2dea6d8fb3",
      icon: "assets/images/fullApps/foodMaster/Pizza_Relhan.png",
      coverm: "aassets/images/fullApps/foodMaster/Pizza_Relhan.png",
      isbookmarked: true,
      timeslotlist: [TimeSlot(id: "8", title: "2pm")],
      openingTime: "5:00 AM",
      closingTime: "11:00 PM",
      deliveryTime: "45 Min",
      blurUrl: "LEG%_H}=02Rl4o-S^*xF2vo|IUEM"),
];
