//category model fetch category data from server side
class BreakingNewsModel {
  String? id, image, title, desc;

  BreakingNewsModel({this.id, this.image, this.title, this.desc});
}

List<BreakingNewsModel> breakingNewsList = [
  BreakingNewsModel(
      id: "1",
      image: "assets/images/fullApps/modernNews/breakingNews1.jpg",
      title:
          "4 major financial works you must complete before end of December 2021",
      desc:
          "New Delhi: Before the end of the calendar year, you must complete a lot of tasks that have a direct impact on your finances. Here is a list of 4 major financial works you must complete before end of December 2021.\n\nPF Account NomineeIf you have a Provident Fund account, then you must not ignore this deadline. The Employees' Provident Fund Organisation (EPFO) has made it necessary for all PF account holders to designate a nominee. The deadline for adding the nominee is December 31, 2021. Failure to add a nominee to your PF account by the necessary date can result in a variety of problems, including the loss of benefits such as insurance money and pension. Importantly, PF account holders can add the nominee online, as we describe here.\n\nITR Filing DeadlineThe government had in September extended the deadline till December 31 for filing of income tax returns by individuals for the financial year 2021, amid the coronavirus pandemic and technical glitches in the IT portal. Earlier, the deadline was extended to September 30, 2021. Usually, the last date for filing the ITR (Income Tax Returns) for the individual taxpayers is July 31.\n\nSubmission of Life Certificate for pensionersThe Ministry of Personnel, Public Grievances & Pension has extended the deadline of submission of Life Certificate to December 31 from the previous deadline of November 30, 2021. It must be noted that that every Central Government Retired Employee is required to submit life certificate in the month of November for continuation of his/her pension. Hence, in view of the ongoing Covid-19 pandemic in various states and keeping in view of the vulnerability of elderly population to Corona Virus, the ministry has now been decided to extend the existing timeline for submission of Life Certificate for all age group of pensioners from 30/11/2021 onwards. Now, all Central Government pensioners may submit Life Certificate till 31st December, 2021.\n\nEPFO's Aadhaar and UAN deadlineThe Employees' Provident Fund Organisation (EPFO) has extended deadline for Aadhaar linking of UAN till December 31, 2021 for Establishments in NORTH EAST and certain class of establishments. Issuing a circular, the EPFO said, \"...after allowing sufficient time of almost four years for Aadhaar seeding, EPFO issued instructions dated 01.06.2021 cited above mandating that UANs is to be Aadhaar seeded for receipt of contributions through ECR. However, considering the challenges faced by the employers & employees in expeditious seeding of Aadhaar in UANs particularly in view of corrections required in Aadhaar data of employees in aftermath of second wave of Pandemic, the EPFO with prior approval of the Central Government extended the time for mandatory seeding of Aadhaar in UAN for filing ECR up to 01.09.2021 which was communicated vide reference cited 2 above.\" "),
  BreakingNewsModel(
      id: "2",
      image: "assets/images/fullApps/modernNews/breakingNews2.jpg",
      title:
          "Delhi nursery admission 2022-23: Registration begins today, check important dates and other details",
      desc:
          "According to a notification issued by the Directorate of Education last month, the process of nursery admissions will begin from today (December 15, 2021) in nearly 1,800 private schools across the national capital. The application window is scheduled to close on January 7. \n\nNEW DELHI: The registration process for admissions into nursery classes for the 2022-23 academic session will begin in the private, unaided and recognised schools in the national capital from Wednesday (December 15, 2021). While most of the schools are selling admission forms online, the same can also be purchased directly from the school premises for the convenience of parents.\n\nAccording to a notification issued by the Directorate of Education (DoE) last month, the process of nursery admissions will begin from today (December 15, 2021) in nearly 1,800 private schools across the national capital. The application window is scheduled to close on January 7.\n\nThe admission to entry-level classes for the previous academic session began in February this year after a delay due to the COVID-19 pandemic. However, this year, the schedule is in line with previous years.DoE notification for admission\n\nThe DoE had last month notified the admission schedule. As per the notified schedule, the first list of selected children will be put up on February 4, followed by a second list on February 21 and a subsequent list for admission, if any, on March 15. The entire admission process will conclude on March 31.Criterion for nursery admission\n\nThe DoE has asked the schools to notify their number of seats and the admission criteria by Tuesday. The DoE has directed that the number of seats at the entry levels shall not be less than the highest number of seats in entry-level classes during the last three years-- 2019-20, 2020-21 and 2021-22.\n\n\"Schools shall develop and adopt criteria for admission which shall be fair, reasonable, well defined, equitable, non-discriminatory, unambiguous and transparent,’’ the DoE said.\n\n"),
  BreakingNewsModel(
      id: "3",
      image: "assets/images/fullApps/modernNews/breakingNews3.jpg",
      title: "Working hours may change in Mumbai due to global warming",
      desc:
          "MUMBAI: The city may need to shift working hours to morning or evening if current trends in pollution or carbon emissions and the resulting warming continue. According to a study published by Duke University in an international journal “Nature Communications”, current temperatures show a loss of about 4 to 5 minutes per hour due to the hot and humid weather in Mumbai. This means a loss of one hour during 12 hours of work.\n\nWith global warming increasing by one degree each, the same can double to 10 minutes per hour, the newspaper warns. The loss of working hours per hour is around 12 minutes in Ahmedabad while Chennai and Hyderabad are close to Mumbai.\n\nThe current temperature begins to rise above 26 degrees Celsius from noon. Thus, each additional degree of global warming will result in greater and greater loss of labor, and moving heavy labor to the cooler hours of the day will become less efficient as the world is heating up, reveals the paper.\n\n“There are physiological limits to the heat / humidity combinations that humans can tolerate. On a larger scale, the world is currently losing \$ 280-311 billion a year due to workers struggling in hot and humid conditions, and if the world becomes 2 ° C warmer than today (around 3 ° C above pre-industrial levels), these losses would increase. to \$ 1.6 trillion, ”the study said.Global warming will cause more acute labor losses in the tropics and subtropics, but will also have a growing impact on mid-latitudes, the document said. Each degree of warming results in exponential and non-linear losses in labor productivity. For example, the number of hours lost in the 12-hour workday drops from 101 billion hours per ° C over the past 42 years to 197 billion hours per ° C (+/- 11 billion hours) with an additional 2 ° C of warming, the study suggests.\n\nThis is the first worldwide study to assess the effectiveness of moving heavy work to the cooler times of the day as an adaptation to climate change. Currently, moving the workforce out of the hottest 3 hours of the day can recoup about 30% of lost productivity. However, this can cause other problems, for example due to poor sleep in increasingly hot and humid weather.\n\nThe possibility of adapting to climate change by moving some work to cooler hours decreases by about 2% with each additional degree of warming. Under an additional 2 ° C of future warming (total about 3 ° C above pre-industrial levels), more of the global workforce would be lost in the cooler 12 hours of the day than it is currently lost during the hottest 12 hours of the day. All results are conservative, as they reflect conditions in shade – conditions in full sun will be much worse.\n\n"),
  BreakingNewsModel(
      id: "4",
      image: "assets/images/fullApps/modernNews/breakingNews2.jpg",
      title: "Opinion: No, Modi Does Not Use Religion For Politics",
      desc:
          "So the world saw a different Modi. Here was a leader who was accused by his opponents of bigotry and communalism, presenting himself as a man with a vision for making the country great again with development was his forte. Overnight, the 'Gujarat Model' became dominant in the political lexicon. A carefully-crafted image of a man obsessed with development was projected and it was seeded into the national consciousness that he was not what the Opposition was branding him as. \n\nModi most brilliantly used development, a secular value in a secular democracy, as political currency; his genius lay in the fact that he let this secular value overwhelm his Hindu leader image. But once he reached the top, he used every instrument of power to create a - narrative about the country needing a religious awakening, with Hindus needing to assert their dominance in their own country. In this endeavour, he ruthlessly used TV as a medium as it magnified manifold the visual impact of the Hindu grandeur. The live telecast of the inauguration of Ram Temple in Ayodhya and now in Kashi is part of that design.\n\nFor Modi, Ayodhya and Kashi is not politics but a matter of faith. It is an exercise to correct the wrongs of history as he perceives it. It is an attempt to teach a lesson to the followers of Islam that India is no longer a country where their writ will run disproportionately; India is primarily a Hindu nation, and Muslims have no option but to accept that fact and live with the guilt that their ancestors committed great sins in this country. The reference to Aurangzeb in Kashi is deliberate. Shiva-ji is used as metaphor for the assertion and rise of Hindu power. This mesmerises a section of Hindus because Modi visually takes them on a pilgrimage to the past. \n\nWhen I was researching my last book, Hindu Rashtra, I was aghast to know that many big names of academia and journalism have no understanding of the RSS, have not read their original writings and have a very superficial knowledge about their ideology. It is no accident of history that many of these intellectuals and senior journalists belonging to the liberal school of thought did not see how the world would unfold when Modi became Prime Minister. They were seen singing paeans to Modi. And not surprisingly, many of them later said they regret having supported Modi. They failed to understand that it was not about Modi, but about the RSS and its ideology of Hindutva, which defines history as a 1,200-year-long religious war with Islam, and holds that this war will continue till Islam is vanquished in India. For them, the partition of India is part of a greater Jihadi design. Kashmir, in their opinion, is the unfinished agenda of Islamist forces. The government at the centre is not there to rule, or to provide development for millions, but it is there to seek revenge for partition and for the past. The regular references to 'internal enemies' are a pointer in that direction."),
];
