// ignore_for_file: unnecessary_string_escapes

import 'package:smartkit_pro/ui/fullApps/modernNewsApp/Model/Survey.dart';

//news and user model data fetch from admin side in json api

class News {
  String? id;

  String? userId;

  String? newsId;

  String? categoryId;
  String? title;

  String? date;

  String? contentType;

  String? contentValue;

  String? image;

  String? desc;

  String? categoryName;

  String? counter;

  String? date_sent;

  String? totalLikes;

  String? like;

  String? keyName;

  String? tagId;

  String? tagName;

  String? dislike;

  String? total_dislike;

  String? subCat_id;

  List<ImageData>? imageDataList;

  bool? history = false;
  String? question, status, type;
  List<Option>? optionDataList;
  int? from;

  News(
      {this.id,
      this.userId,
      this.newsId,
      this.categoryId,
      this.title,
      this.date,
      this.contentType,
      this.contentValue,
      this.image,
      this.desc,
      this.categoryName,
      this.counter,
      this.date_sent,
      this.imageDataList,
      this.totalLikes,
      this.like,
      this.keyName,
      this.tagName,
      this.dislike,
      this.subCat_id,
      this.total_dislike,
      this.tagId,
      this.history,
      this.optionDataList,
      this.question,
      this.status,
      this.type,
      this.from});
}

class ImageData {
  String? otherImage;

  ImageData({this.otherImage});
}

List<News> queResultList = [
  News(
      id: "1",
      question:
          "Which, if any, of the following have you used for reading, watching, sharing or discussing news in the last week?",
      status: "1",
      optionDataList: [
        Option(
            id: "1",
            options: "Facebook",
            percentage: "26.87%",
            questionId: "1"),
        Option(
            id: "2",
            options: "LinkedIn",
            percentage: "13.43%",
            questionId: "1"),
        Option(
            id: "3", options: "Google+", percentage: "8.96%", questionId: "1"),
        Option(
            id: "4", options: "Twitter", percentage: "7.46%", questionId: "1"),
      ],
      type: "survey",
      from: 1)
];

List<News> questionList = [
  News(
      id: "2",
      question: "Which type of news you most like?",
      status: "1",
      optionDataList: [
        Option(id: "1", options: "Top News", percentage: "", questionId: "2"),
        Option(
            id: "2", options: "Entertainment", percentage: "", questionId: "2"),
        Option(id: "3", options: "Health", percentage: "", questionId: "2"),
        Option(id: "4", options: "Sports", percentage: "", questionId: "2"),
      ],
      type: "survey",
      from: 1)
];

List<News> recentNewsList = [
  News(
    id: "11",
    userId: "1",
    newsId: "11",
    categoryId: "5",
    title:
        "Ranveer gives Deepika a peck on the cheek, says ‘she’s my producer'. Watch",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews11.jpg",
    desc:
        "Deepika Padukone and Ranveer Singh were spotted at Mumbai airport early on Wednesday morning. Ranveer kissed Deepika, sending the paparazzi in a tizzy. \n\nDeepika Padukone and Ranveer Singh were spotted at the Mumbai airport early on Wednesday morning and sported contrasting travel looks. Ranveer not only gained attention for his quirky outfit but also indulged in a little PDA as he planted a kiss on Deepika's cheek while posing for the paparazzi. \n\nDeepika opted for a classic look in a black and white top and skirt paired with black boots and bag. She had her hair tied in a ponytail. Ranveer, meanwhile, was in an animal print tee and red velvet bell-bottoms paired with red framed glasses and and a black sling bag.\n\nRanveer got down from the car to get to the other side and opened the door for Deepika. As the two posed for photographs at the airport departure, he looked at Deepika and said “Meri producer hai (she's my producer).\" Deepika co-produces Ranveer's upcoming movie 83, which she also stars in.\n\n",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage:
              "assets/images/fullApps/modernNews/entertainment1Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "12",
    userId: "1",
    newsId: "12",
    categoryId: "5",
    title: "Attack teaser: John Abraham washes off sins of Satyameva Jayate 2",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews12.jpg",
    desc:
        "John Abraham, Jacqueline Fernandez and Rakul Preet feature in Attack teaser which seems to be an action packed revenge drama.\n\nAfter the super debacle of Sayameva Jayate 2, John Abraham is back with what appears to be a comparatively sober action drama, Attack. The teaser of the film is out and shows John in commando mode, taking on enemies after an attack.\n The teaser opens with a bomb blast that throws life out of gear for all those who lose their dear ones. A broken John is seen shell shocked while grieving at the blast site. A worried Jacqueline Fernandez, is seen rushing to the spot in a saree, which is probably the uniform of a flight attendant.\n\nIt is followed by glimpses of John getting some chip implants and a voice declaring, \“all vitals are normal, you are ready to serve soldier.\” Rakul Preet Singh is also seen in a still as choppers fly past her. Action scenes are filled with guns and missiles as John and his team fight in the Parliament. A day before the teaser release, John deleted all posts from his Instagram account without revealing the reason behind it. The actor is all set to celebrate his 49th birthday on December 17.\n\nThe actor removed all of his pictures and videos along with his profile image from Instagram despite having a fan following of over 9 million on the platform. However, John has not deleted his Instagram Reels.\n\nAttack is set to release on Republic Day, January 26, next year. The film has been directed and written by Lakshya Raj Anand. Ratna Pathak Shah, Prakash Raj, Vikas Sharma and Shefali Ganguly are also said to be a part of the film. \n\n",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "13",
    userId: "1",
    newsId: "13",
    categoryId: "4",
    title: "COVID-19: Why the Omicron variant has scientists worried",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/healthNews39.jpg",
    desc:
        "Scientists have detected cases of a new variant of SARS-CoV-2, which is the virus that causes COVID-19, in a number of countries. Omicron (B.1.1.529) has an unprecedentedly large number of mutations in the part of its genome that encodes a key section of its spike protein, which the virus uses to infect host cells. This suggests that Omicron may be able to evade some of the immune protection afforded by vaccines, many of which are based on the original spike protein, and past infections.\n\nOn November 16, 2021, there were 136 daily recorded cases of COVID-19 in South Africa. By November 25, 2021, that number had risen to over 1,200.\n\nMore than 80% of these cases were in the densely populated province of Gauteng, which includes Johannesburg and Pretoria.\n\nResearchers estimated that the R-value, which is the average number of new cases caused by each infection, was 1.47 for South Africa as a whole.\n\nIf R is more than 1, an outbreak will grow exponentially. In Gauteng province, R was 1.93.\n\nScientists at the Centre for Epidemic Response and Innovation (CERI) in Stellenbosch, South Africa, believe that a new variant of the virus known as Omicron (B.1.1.529) is responsible for these worrying figures.\n\nThere have been three previous peaks of infection in South Africa during the course of the pandemic, with the third due to the Delta variant. The latest surge coincides with the first detection of Omicron by scientists.\n\nScientists have sequenced around 100 confirmed cases of Omicron infection in South Africa. Most of the cases have been in Gauteng.\n\nThe new variant is also present in Botswana, Hong Kong, Europe, Canada, Israel, Japan, the United States, and elsewhere.\n\n",
    categoryName: "Health",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona",
    dislike: "0",
    subCat_id: "1",
    total_dislike: "",
    tagId: "1",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "14",
    userId: "1",
    newsId: "14",
    categoryId: "3",
    title:
        "Manchester United's Premier League match against Brentford postponed due to Covid-19 outbreak within squad",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews14.jpg",
    desc:
        "Manchester United had reported a \"small number\" of cases discovered among first-team staff and players on Sunday, with the players who travelled to Norwich City for their Premier League clash on Saturday kept apart from those who had the virus.\n\nHIGHLIGHTS\nThe Premier League found a record 42 cases of COVID-19 among players and staff at various clubs\n\nThe 42 positive tests from over 3,800 individuals is more than the tally from the previous seven weeks combined\n\nBrentford said they welcomed the decision to postpone Tuesday's match\n\nManchester United's Premier League match at Brentford on Tuesday has been postponed due to a number of COVID-19 cases at the Old Trafford club, the league announced on Monday.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "FootBall",
    dislike: "0",
    subCat_id: "6",
    total_dislike: "",
    tagId: "6",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "15",
    userId: "1",
    newsId: "15",
    categoryId: "3",
    title:
        "Barcelona forward Sergio Aguero set to announcement retirement following heart evaluation",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews15.jpg",
    desc:
        "Sergio Aguero was told by doctors to rest for three months after suffering chest pains during Barcelona's 1-1 draw against Alaves in the La Liga on October 30.\n\nHIGHLIGHTS\n\nSergio Aguero will make a statement on his future at the Nou Camp on Wednesday\nThe 33-year-old Argentina striker has been receiving treatment for a heart condition.\nAguero has made 5 appearances in all competitions for Barcelona so far since arriving from Man City\n\nBarcelona forward Sergio Aguero is likely to announce his retirement from football on December 15, reports in Spanish media suggested on Tuesday. Aguero's future as a professional footballer could be cut short after being diagnosed with a heart arrhythmia.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "FootBall",
    dislike: "0",
    subCat_id: "5",
    total_dislike: "",
    tagId: "6",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "19",
    userId: "1",
    newsId: "19",
    categoryId: "3",
    title:
        "India's Tour Of South-Africa: Virat Kohli Press Conference Live Updates: Available For ODI Series, Never Asked For Rest, Says Test Skipper",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews19.jpg",
    desc:
        "Virat Kohli Press Conference Live Updates: Indian Test skipper Virat Kohli will address the media ahead of Team India's upcoming South Africa tour, scheduled to begin from December 26.\n\nVirat Kohli Press Conference Live Updates: Indian Test skipper Virat Kohli is addressing the media ahead of Team India's upcoming South Africa tour, scheduled to begin from December 26. Kohli has clarified that he will be available for the three-match ODI series and had never asked for a break, contrary to media reports. The opening Test match will be played in Centurion at the SuperSport Park from December 26 to 30. Johannesburg's Wanderers Stadium will be the host to the second Test between January 3 to 7 next year. The third and final Test will be played in Newlands in Cape Town between January 11 to 15. Other than the Tests, India will also engage in a three-match ODI series while the T20I series was rescheduled for later.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/sports6Data1.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/Sports6Data2.jpg"),
      ImageData(otherImage: "assets/images/fullApps/modernNews/world1Data2.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Cricket,India",
    dislike: "0",
    subCat_id: "7",
    total_dislike: "",
    tagId: "4,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "20",
    userId: "1",
    newsId: "20",
    categoryId: "1",
    title: "NIA arrests one more Afghan national in 3,000-kg drug haul case",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/topNewsNews20.jpg",
    desc:
        "The National Investigation Agency (NIA) has arrested another Afghan national in connection with the 3,000-kg heroin seizure by the Directorate of Revenue Intelligence (DRI) at Mundra port in Gujarat in September.\n\nThe accused has been identified as Sobhan Aryanfar (28). The agency arrested him from Neb Sarai in south Delhi.\n\nAccording to the NIA, Aryanfar has been found to be involved in the conspiracy to transport narcotic drugs concealed in the import consignment of semi-processed talc stones, which had originated from Afghanistan.\n\nThe agency has registered the case under the Unlawful Activities (Prevention) Act and the relevant provisions of the Narcotic Drugs and Psychotropic Substances Act and the Indian Penal Code, on the basis of the findings of the DRI.\n\nThe NIA officials suspect that the same network had been used to smuggle in another consignment in the past.\n\nSome of the accused persons are said to be linked to a drug trafficking case registered earlier by the Special Cell of the Delhi Police.\n\nBased on the inputs, the NIA had conducted searches in different parts of the country, including in and around Delhi, in October. It collected samples of suspected drugs from a warehouse.\n\nEarlier, the DRI arrested 10 persons, including six Afghan nationals and an Uzbek woman, for their alleged involvement.\n\nThe DRI probe revealed that the contraband had been packed in Afghanistan and sent through Kandahar-based Hassan Hussain Limited. The consignment was declared as that of talc stones for export to Aashi Trading Company in Vijayawada, via Bandar Abbas port in Iran.\n\nThe drugs were meant to be brought to Delhi for further transportation and distribution.",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "21",
    userId: "21",
    newsId: "1",
    categoryId: "1",
    title:
        "Man from Nigeria with COVID-19 admitted to King Institute, Omicron suspected, says TN Health Minister",
    date: "15-Dec-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/health2Data4.jpg",
    desc:
        "A man who travelled to Tamil Nadu from Nigeria and six of his family members, with COVID-19, have been admitted to the King Institute of Preventive Medicine in Chennai, Health Minister Ma. Subramanian said in Tiruchi on Tuesday. The man had landed at the Chennai International Airport two days ago from Nigeria via Doha. He was randomly subjected to the RT-PCR test. The 47-year-old patient was detected with the ‘S’ gene drop out, one of the early indicators of the Omicron variant.\n\nFollowing this, his six other family members, were subjected to COVID-19 testing. They were also subsequently detected with the ‘S’ gene drop out. Since the preliminary analysis showed the possibility of the Omicron variant, they have been admitted to the King Institute. All of them are asymptomatic.They were under close surveillance, Mr. Subramanian told reporters after visiting the K.A.P. Viswanatham Medical College Hospital.\n\nMr. Subramanian said the samples had been sent to a laboratory in Bengaluru for genome sequencing tests. The results were expected on Tuesday evening or Wednesday. The State had so far sent samples of 29 other patients to Bengaluru to check for Omicron. Four of them had turned out to be cases of the Delta variant.\n\nThe Health Minister said that the State had 79 RT-PCR testing facilities. It had a capacity to screen 1.88 lakh patients a day. Twenty more RT-PCR machines had been procured for district headquarters hospitals and medical college hospitals to ramp up the testing facilities.\n\n",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "1",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "22",
    userId: "22",
    newsId: "1",
    categoryId: "1",
    title: "4 more Omicron cases detected in Delhi: Satyendar Jain",
    date: "15-Dec-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/topNewsNews22.jpeg",
    desc:
        "Delhi Health Minister Satyendar Jain on Tuesday said four more cases of the new COVID-19 variant, Omicron, have been detected in the national capital and all have travel history to foreign countries.\n\nThe Omicron variant of the coronavirus has not spread in the community so far and the situation is under control, he added.\n\nMr. Jain said the government is fully prepared to tackle the spread of any variant of the coronavirus.\n\n\"So far, six people have been found Omicron positive in the capital. One of them has been discharged. All of them had travelled to foreign countries and were transferred to the Lok Nayak Jai Prakash Narayan (LNJP) hospital from the (Indira Gandhi International) airport,\" Mr. Jain told reporters.\n\nSo far, 74 travellers have been sent from the airport to the hospital, where a special ward has been set up for isolating and treating suspected cases of Omicron. Thirty-six of them have been discharged and 38 are admitted to the hospital.\n\nDelhi's first patient of the Omicron variant —a 37-year-old man from Ranchi— was discharged from the LNJP hospital on Monday after he tested negative for COVID-19 twice, officials said.\n\nThe man had travelled from Tanzania to Doha and from there, to Delhi on a Qatar Airways flight on December 2. He stayed in Johannesburg in South Africa for a week and had mild symptoms.\n\nThe condition of the remaining five Omicron-positive patients is stable, Mr. Jain said.\n\nUnder new norms, RT-PCR tests are mandatory for the passengers arriving from the \"at-risk\"\n countries and they are allowed to leave the airport only after the results come.\nAlso, two per cent of the passengers arriving on flights from other countries are being tested randomly.\n\n",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "30",
    userId: "1",
    newsId: "30",
    categoryId: "5",
    title: "Bigg Boss 15: Jay Bhanushali to enter Salman Khan's reality show?",
    date: "01-Oct-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews30.png",
    desc:
        "Another celebrity to join Salman Khan's show Bigg Boss 15 is TV actor Jay Bhanushali. Going by the latest reports, the actor has signed the dotted line and will enter the controversial show along with other contestants. \n\nWith just a few hours left for the grand premiere of the controversial reality show Bigg Boss 15, names of celebrities entering the house have been going viral on the internet. While celebrities like Umar Riaz, Tejasswi, Karan Kundrra, Sahil Shroff, and others have been confirmed, speculations about others are still going on. Another name that has popped on the internet to join Salman Khan's show is TV actor Jay Bhanushali. Going by the latest reports, the actor has signed the dotted line and will enter the show along with other contestants.\n\nJay Bhanushali has been seen on Bigg Boss many times before as a guest. He has not only entertained the fans with his perfect comic timing but also encouraged the contestants during his visits. A report in ETimes claims that Jay gave his nod a day before the show begins. It quoted a source saying, \"We were looking for a couple of popular TV actors and the deal with Jay materialised just a day before the contestants had to go inside the house.\"\n\nJay Bhanushali is a popular name on the small screen. Other than proving his acting mettle with high TRP daily soaps, the actor has been a part of reality shows as well. He has earlier participated in Jhalak Dikhhla Jaa, Kaun Jeetega Bollywood Ka Ticket, Iss Jungle Se Mujhe Bachao, Nachle Ve With Saroj Khan, Nach Baliye 5, and Fear Factor: Khatron Ke Khiladi 7.\n\nJay has been a part of TV shows like Kayamath, Kis Desh Mein Hai Meraa Dil, Geet - Hui Sabse Parayi and Kairi - Rishta Khatta Meetha.\n\nJay is married to actress Mahhi Vij. The duo had tied the knot in 2010 and their daughter Tara was born on August 21, 2019. They had also adopted their caretaker's kids, Khushi and Rajveer, in 2017.\n\nBesides Jay Bhanushali, Donal Bisht, Shamita Shetty and Nishant Bhat will also be locked in the 'BB15' house. Pratik Sehajpal is also the confirmed contestant from 'Bigg Boss OTT'. Others are Karan Kundra, Simba Nagpal, Sahil Shroff, Vidhi Pandya, Vishal Kotian.\n\nThe show's tagline is 'Sankat in Jungle, Phailaayega Dangal Pe Dangal'",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity,India",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "36",
    userId: "1",
    newsId: "36",
    categoryId: "1",
    title: "Meril gets nod from ICMR for its indigenous Covid-19 self-test kit",
    date: "18-Jun-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/healthNews36.jpg",
    desc:
        "Meril has got ICMR approval for its self-use rapid antigen test for Covid-19, CoviFind. The test delivers results in 15 minutes, Meril said in a statement.\n\nMedtech firm Meril has said it has received approval from the Indian Council of Medical Research (ICMR) for its self-use rapid antigen test kit for Covid-19.\n\nMeril’s indigenous home-use rapid antigen test kits \“CoviFind\” will expand access to Covid-19 testing, while also helping the nation meet the demand for increased and frequent screening to curb the spread of the pandemic, Meril said in a statement.\n\nThe test delivers results swiftly, providing accurate results in 15 minutes, it added.\n\n\“By making reliable rapid antigen testing available to all through a convenient format, Meril''s CoviFind test will facilitate early detection, isolation, treatment and contact tracing,\" Meril Senior Vice-President (Corporate Strategy) Sanjeev Bhatt said.\n\nMeril said it has supplied a large number of tests across its Covid-19 diagnostics offerings across India, which include a multiplex RT-PCR test, Kavach antibody tests in partnership with ICMR.\n\nWhat will the test include?\n\nThe test kit is equipped with testing materials including a test device, one sterile nasal swab and a pre-filled buffer tube with a cap and is priced at Rs 250 as an affordable single-pack, the company said.",
    categoryName: "Health",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data1.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data2.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data3.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data4.jpg"),
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona,India",
    dislike: "0",
    subCat_id: "7",
    total_dislike: "",
    tagId: "1,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "39",
    userId: "1",
    newsId: "39",
    categoryId: "4",
    title:
        "Media reports alleging Centre hasn't placed any fresh order for COVID-19 vaccines incorrect: Health Ministry",
    date: "03-May-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/healthNews39.jpg",
    desc:
        "Apple has been listed as a client by a UK-based firm that manufactures photonics chips. Based on the work of the company, it is expected to supply glucose monitoring sensors to Apple for its Apple Watch in the coming years.\n\nHIGHLIGHTS\n\nRockley Photonics has listed Apple as one of its few large customers.\nThe company manufactures sensors that can monitor a person's blood using infrared light.\nThe firm has a \"supply and development agreement\" with Apple.\nApple might have a big feature lined up for the future iterations of the Apple Watch. As per a recent SEC filing, it seems that upcoming models of Apple Watch will have glucose monitoring capabilities on them.",
    categoryName: "Health",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health4Data1.jpg"),
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona,India",
    dislike: "0",
    subCat_id: "1",
    total_dislike: "",
    tagId: "1,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "50",
    userId: "1",
    newsId: "50",
    categoryId: "6",
    title:
        "New Zealand suspends ties with Myanmar after coup, puts travel ban on military leaders",
    date: "09-Feb-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/worldNews50.jpg",
    desc:
        "ew Zealand is suspending all high-level contact with Myanmar and imposing a travel ban on its military leaders following last week's coup, Prime Minister Jacinda Ardern said on Tuesday.\n\nNew Zealand will also ensure its aid programme will not include projects that are delivered with, or benefit, the military government, Ardern told a news conference.\n\n\"Our strong message is we will do what we can from here in New Zealand and one of the things we will do is suspend that high-level dialogue...and make sure any funding we put into Myanmar does not in any way support the military regime,\" Ardern said.\n\nNew Zealand's aid programme was worth about NZ\$42 million (\$30 million) between 2018 and 2021, she said.",
    categoryName: "World",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(otherImage: "assets/images/fullApps/modernNews/world6Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "51",
    userId: "1",
    newsId: "51",
    categoryId: "6",
    title:
        "Aung San Suu Kyi, other leaders detained as military declares one year emergency in Myanmar",
    date: "01-Feb-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/worldNews51.jpg",
    desc:
        "The intervention came after weeks of rising tensions between the military, which ruled the country for nearly five decades, and the civilian government over allegations of fraud in November's elections.\n\nMyanmar's military staged a coup on Monday, detaining de facto leader Aung San Suu Kyi and declaring it had taken control of the country for one year under a state of emergency.",
    categoryName: "World",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(otherImage: "assets/images/fullApps/modernNews/world7Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
];

List<News> userNewsList = tempUserNewsList.reversed.toList();

List<News> tempUserNewsList = [
  News(
    id: "11",
    userId: "1",
    newsId: "11",
    categoryId: "5",
    title:
        "Ranveer gives Deepika a peck on the cheek, says ‘she’s my producer'. Watch",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews11.jpg",
    desc:
        "Deepika Padukone and Ranveer Singh were spotted at Mumbai airport early on Wednesday morning. Ranveer kissed Deepika, sending the paparazzi in a tizzy. \n\nDeepika Padukone and Ranveer Singh were spotted at the Mumbai airport early on Wednesday morning and sported contrasting travel looks. Ranveer not only gained attention for his quirky outfit but also indulged in a little PDA as he planted a kiss on Deepika's cheek while posing for the paparazzi. \n\nDeepika opted for a classic look in a black and white top and skirt paired with black boots and bag. She had her hair tied in a ponytail. Ranveer, meanwhile, was in an animal print tee and red velvet bell-bottoms paired with red framed glasses and and a black sling bag.\n\nRanveer got down from the car to get to the other side and opened the door for Deepika. As the two posed for photographs at the airport departure, he looked at Deepika and said “Meri producer hai (she's my producer).\" Deepika co-produces Ranveer's upcoming movie 83, which she also stars in.\n\n",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage:
              "assets/images/fullApps/modernNews/entertainment1Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "12",
    userId: "1",
    newsId: "12",
    categoryId: "5",
    title: "Attack teaser: John Abraham washes off sins of Satyameva Jayate 2",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews12.jpg",
    desc:
        "John Abraham, Jacqueline Fernandez and Rakul Preet feature in Attack teaser which seems to be an action packed revenge drama.\n\nAfter the super debacle of Sayameva Jayate 2, John Abraham is back with what appears to be a comparatively sober action drama, Attack. The teaser of the film is out and shows John in commando mode, taking on enemies after an attack.\n The teaser opens with a bomb blast that throws life out of gear for all those who lose their dear ones. A broken John is seen shell shocked while grieving at the blast site. A worried Jacqueline Fernandez, is seen rushing to the spot in a saree, which is probably the uniform of a flight attendant.\n\nIt is followed by glimpses of John getting some chip implants and a voice declaring, \“all vitals are normal, you are ready to serve soldier.\” Rakul Preet Singh is also seen in a still as choppers fly past her. Action scenes are filled with guns and missiles as John and his team fight in the Parliament. A day before the teaser release, John deleted all posts from his Instagram account without revealing the reason behind it. The actor is all set to celebrate his 49th birthday on December 17.\n\nThe actor removed all of his pictures and videos along with his profile image from Instagram despite having a fan following of over 9 million on the platform. However, John has not deleted his Instagram Reels.\n\nAttack is set to release on Republic Day, January 26, next year. The film has been directed and written by Lakshya Raj Anand. Ratna Pathak Shah, Prakash Raj, Vikas Sharma and Shefali Ganguly are also said to be a part of the film. \n\n",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "13",
    userId: "1",
    newsId: "13",
    categoryId: "4",
    title: "COVID-19: Why the Omicron variant has scientists worried",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/healthNews39.jpg",
    desc:
        "Scientists have detected cases of a new variant of SARS-CoV-2, which is the virus that causes COVID-19, in a number of countries. Omicron (B.1.1.529) has an unprecedentedly large number of mutations in the part of its genome that encodes a key section of its spike protein, which the virus uses to infect host cells. This suggests that Omicron may be able to evade some of the immune protection afforded by vaccines, many of which are based on the original spike protein, and past infections.\n\nOn November 16, 2021, there were 136 daily recorded cases of COVID-19 in South Africa. By November 25, 2021, that number had risen to over 1,200.\n\nMore than 80% of these cases were in the densely populated province of Gauteng, which includes Johannesburg and Pretoria.\n\nResearchers estimated that the R-value, which is the average number of new cases caused by each infection, was 1.47 for South Africa as a whole.\n\nIf R is more than 1, an outbreak will grow exponentially. In Gauteng province, R was 1.93.\n\nScientists at the Centre for Epidemic Response and Innovation (CERI) in Stellenbosch, South Africa, believe that a new variant of the virus known as Omicron (B.1.1.529) is responsible for these worrying figures.\n\nThere have been three previous peaks of infection in South Africa during the course of the pandemic, with the third due to the Delta variant. The latest surge coincides with the first detection of Omicron by scientists.\n\nScientists have sequenced around 100 confirmed cases of Omicron infection in South Africa. Most of the cases have been in Gauteng.\n\nThe new variant is also present in Botswana, Hong Kong, Europe, Canada, Israel, Japan, the United States, and elsewhere.\n\n",
    categoryName: "Health",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona",
    dislike: "0",
    subCat_id: "1",
    total_dislike: "",
    tagId: "1",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "14",
    userId: "1",
    newsId: "14",
    categoryId: "3",
    title:
        "Manchester United's Premier League match against Brentford postponed due to Covid-19 outbreak within squad",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews14.jpg",
    desc:
        "Manchester United had reported a \"small number\" of cases discovered among first-team staff and players on Sunday, with the players who travelled to Norwich City for their Premier League clash on Saturday kept apart from those who had the virus.\n\nHIGHLIGHTS\nThe Premier League found a record 42 cases of COVID-19 among players and staff at various clubs\n\nThe 42 positive tests from over 3,800 individuals is more than the tally from the previous seven weeks combined\n\nBrentford said they welcomed the decision to postpone Tuesday's match\n\nManchester United's Premier League match at Brentford on Tuesday has been postponed due to a number of COVID-19 cases at the Old Trafford club, the league announced on Monday.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "FootBall",
    dislike: "0",
    subCat_id: "6",
    total_dislike: "",
    tagId: "6",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "15",
    userId: "1",
    newsId: "15",
    categoryId: "3",
    title:
        "Barcelona forward Sergio Aguero set to announcement retirement following heart evaluation",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews15.jpg",
    desc:
        "Sergio Aguero was told by doctors to rest for three months after suffering chest pains during Barcelona's 1-1 draw against Alaves in the La Liga on October 30.\n\nHIGHLIGHTS\n\nSergio Aguero will make a statement on his future at the Nou Camp on Wednesday\nThe 33-year-old Argentina striker has been receiving treatment for a heart condition.\nAguero has made 5 appearances in all competitions for Barcelona so far since arriving from Man City\n\nBarcelona forward Sergio Aguero is likely to announce his retirement from football on December 15, reports in Spanish media suggested on Tuesday. Aguero's future as a professional footballer could be cut short after being diagnosed with a heart arrhythmia.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "FootBall",
    dislike: "0",
    subCat_id: "5",
    total_dislike: "",
    tagId: "6",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "19",
    userId: "1",
    newsId: "19",
    categoryId: "3",
    title:
        "India's Tour Of South-Africa: Virat Kohli Press Conference Live Updates: Available For ODI Series, Never Asked For Rest, Says Test Skipper",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews19.jpg",
    desc:
        "Virat Kohli Press Conference Live Updates: Indian Test skipper Virat Kohli will address the media ahead of Team India's upcoming South Africa tour, scheduled to begin from December 26.\n\nVirat Kohli Press Conference Live Updates: Indian Test skipper Virat Kohli is addressing the media ahead of Team India's upcoming South Africa tour, scheduled to begin from December 26. Kohli has clarified that he will be available for the three-match ODI series and had never asked for a break, contrary to media reports. The opening Test match will be played in Centurion at the SuperSport Park from December 26 to 30. Johannesburg's Wanderers Stadium will be the host to the second Test between January 3 to 7 next year. The third and final Test will be played in Newlands in Cape Town between January 11 to 15. Other than the Tests, India will also engage in a three-match ODI series while the T20I series was rescheduled for later.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/sports6Data1.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/Sports6Data2.jpg"),
      ImageData(otherImage: "assets/images/fullApps/modernNews/world1Data2.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Cricket,India",
    dislike: "0",
    subCat_id: "7",
    total_dislike: "",
    tagId: "4,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "20",
    userId: "1",
    newsId: "20",
    categoryId: "1",
    title: "NIA arrests one more Afghan national in 3,000-kg drug haul case",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/topNewsNews20.jpg",
    desc:
        "The National Investigation Agency (NIA) has arrested another Afghan national in connection with the 3,000-kg heroin seizure by the Directorate of Revenue Intelligence (DRI) at Mundra port in Gujarat in September.\n\nThe accused has been identified as Sobhan Aryanfar (28). The agency arrested him from Neb Sarai in south Delhi.\n\nAccording to the NIA, Aryanfar has been found to be involved in the conspiracy to transport narcotic drugs concealed in the import consignment of semi-processed talc stones, which had originated from Afghanistan.\n\nThe agency has registered the case under the Unlawful Activities (Prevention) Act and the relevant provisions of the Narcotic Drugs and Psychotropic Substances Act and the Indian Penal Code, on the basis of the findings of the DRI.\n\nThe NIA officials suspect that the same network had been used to smuggle in another consignment in the past.\n\nSome of the accused persons are said to be linked to a drug trafficking case registered earlier by the Special Cell of the Delhi Police.\n\nBased on the inputs, the NIA had conducted searches in different parts of the country, including in and around Delhi, in October. It collected samples of suspected drugs from a warehouse.\n\nEarlier, the DRI arrested 10 persons, including six Afghan nationals and an Uzbek woman, for their alleged involvement.\n\nThe DRI probe revealed that the contraband had been packed in Afghanistan and sent through Kandahar-based Hassan Hussain Limited. The consignment was declared as that of talc stones for export to Aashi Trading Company in Vijayawada, via Bandar Abbas port in Iran.\n\nThe drugs were meant to be brought to Delhi for further transportation and distribution.",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "21",
    userId: "21",
    newsId: "1",
    categoryId: "1",
    title:
        "Man from Nigeria with COVID-19 admitted to King Institute, Omicron suspected, says TN Health Minister",
    date: "15-Dec-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/health2Data4.jpg",
    desc:
        "A man who travelled to Tamil Nadu from Nigeria and six of his family members, with COVID-19, have been admitted to the King Institute of Preventive Medicine in Chennai, Health Minister Ma. Subramanian said in Tiruchi on Tuesday. The man had landed at the Chennai International Airport two days ago from Nigeria via Doha. He was randomly subjected to the RT-PCR test. The 47-year-old patient was detected with the ‘S’ gene drop out, one of the early indicators of the Omicron variant.\n\nFollowing this, his six other family members, were subjected to COVID-19 testing. They were also subsequently detected with the ‘S’ gene drop out. Since the preliminary analysis showed the possibility of the Omicron variant, they have been admitted to the King Institute. All of them are asymptomatic.They were under close surveillance, Mr. Subramanian told reporters after visiting the K.A.P. Viswanatham Medical College Hospital.\n\nMr. Subramanian said the samples had been sent to a laboratory in Bengaluru for genome sequencing tests. The results were expected on Tuesday evening or Wednesday. The State had so far sent samples of 29 other patients to Bengaluru to check for Omicron. Four of them had turned out to be cases of the Delta variant.\n\nThe Health Minister said that the State had 79 RT-PCR testing facilities. It had a capacity to screen 1.88 lakh patients a day. Twenty more RT-PCR machines had been procured for district headquarters hospitals and medical college hospitals to ramp up the testing facilities.\n\n",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "1",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "22",
    userId: "22",
    newsId: "1",
    categoryId: "1",
    title: "4 more Omicron cases detected in Delhi: Satyendar Jain",
    date: "15-Dec-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/topNewsNews22.jpeg",
    desc:
        "Delhi Health Minister Satyendar Jain on Tuesday said four more cases of the new COVID-19 variant, Omicron, have been detected in the national capital and all have travel history to foreign countries.\n\nThe Omicron variant of the coronavirus has not spread in the community so far and the situation is under control, he added.\n\nMr. Jain said the government is fully prepared to tackle the spread of any variant of the coronavirus.\n\n\"So far, six people have been found Omicron positive in the capital. One of them has been discharged. All of them had travelled to foreign countries and were transferred to the Lok Nayak Jai Prakash Narayan (LNJP) hospital from the (Indira Gandhi International) airport,\" Mr. Jain told reporters.\n\nSo far, 74 travellers have been sent from the airport to the hospital, where a special ward has been set up for isolating and treating suspected cases of Omicron. Thirty-six of them have been discharged and 38 are admitted to the hospital.\n\nDelhi's first patient of the Omicron variant —a 37-year-old man from Ranchi— was discharged from the LNJP hospital on Monday after he tested negative for COVID-19 twice, officials said.\n\nThe man had travelled from Tanzania to Doha and from there, to Delhi on a Qatar Airways flight on December 2. He stayed in Johannesburg in South Africa for a week and had mild symptoms.\n\nThe condition of the remaining five Omicron-positive patients is stable, Mr. Jain said.\n\nUnder new norms, RT-PCR tests are mandatory for the passengers arriving from the \"at-risk\"\n countries and they are allowed to leave the airport only after the results come.\nAlso, two per cent of the passengers arriving on flights from other countries are being tested randomly.\n\n",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "30",
    userId: "1",
    newsId: "30",
    categoryId: "5",
    title: "Bigg Boss 15: Jay Bhanushali to enter Salman Khan's reality show?",
    date: "01-Oct-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews30.png",
    desc:
        "Another celebrity to join Salman Khan's show Bigg Boss 15 is TV actor Jay Bhanushali. Going by the latest reports, the actor has signed the dotted line and will enter the controversial show along with other contestants. \n\nWith just a few hours left for the grand premiere of the controversial reality show Bigg Boss 15, names of celebrities entering the house have been going viral on the internet. While celebrities like Umar Riaz, Tejasswi, Karan Kundrra, Sahil Shroff, and others have been confirmed, speculations about others are still going on. Another name that has popped on the internet to join Salman Khan's show is TV actor Jay Bhanushali. Going by the latest reports, the actor has signed the dotted line and will enter the show along with other contestants.\n\nJay Bhanushali has been seen on Bigg Boss many times before as a guest. He has not only entertained the fans with his perfect comic timing but also encouraged the contestants during his visits. A report in ETimes claims that Jay gave his nod a day before the show begins. It quoted a source saying, \"We were looking for a couple of popular TV actors and the deal with Jay materialised just a day before the contestants had to go inside the house.\"\n\nJay Bhanushali is a popular name on the small screen. Other than proving his acting mettle with high TRP daily soaps, the actor has been a part of reality shows as well. He has earlier participated in Jhalak Dikhhla Jaa, Kaun Jeetega Bollywood Ka Ticket, Iss Jungle Se Mujhe Bachao, Nachle Ve With Saroj Khan, Nach Baliye 5, and Fear Factor: Khatron Ke Khiladi 7.\n\nJay has been a part of TV shows like Kayamath, Kis Desh Mein Hai Meraa Dil, Geet - Hui Sabse Parayi and Kairi - Rishta Khatta Meetha.\n\nJay is married to actress Mahhi Vij. The duo had tied the knot in 2010 and their daughter Tara was born on August 21, 2019. They had also adopted their caretaker's kids, Khushi and Rajveer, in 2017.\n\nBesides Jay Bhanushali, Donal Bisht, Shamita Shetty and Nishant Bhat will also be locked in the 'BB15' house. Pratik Sehajpal is also the confirmed contestant from 'Bigg Boss OTT'. Others are Karan Kundra, Simba Nagpal, Sahil Shroff, Vidhi Pandya, Vishal Kotian.\n\nThe show's tagline is 'Sankat in Jungle, Phailaayega Dangal Pe Dangal'",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity,India",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "36",
    userId: "1",
    newsId: "36",
    categoryId: "1",
    title: "Meril gets nod from ICMR for its indigenous Covid-19 self-test kit",
    date: "18-Jun-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/healthNews36.jpg",
    desc:
        "Meril has got ICMR approval for its self-use rapid antigen test for Covid-19, CoviFind. The test delivers results in 15 minutes, Meril said in a statement.\n\nMedtech firm Meril has said it has received approval from the Indian Council of Medical Research (ICMR) for its self-use rapid antigen test kit for Covid-19.\n\nMeril’s indigenous home-use rapid antigen test kits \“CoviFind\” will expand access to Covid-19 testing, while also helping the nation meet the demand for increased and frequent screening to curb the spread of the pandemic, Meril said in a statement.\n\nThe test delivers results swiftly, providing accurate results in 15 minutes, it added.\n\n\“By making reliable rapid antigen testing available to all through a convenient format, Meril''s CoviFind test will facilitate early detection, isolation, treatment and contact tracing,\" Meril Senior Vice-President (Corporate Strategy) Sanjeev Bhatt said.\n\nMeril said it has supplied a large number of tests across its Covid-19 diagnostics offerings across India, which include a multiplex RT-PCR test, Kavach antibody tests in partnership with ICMR.\n\nWhat will the test include?\n\nThe test kit is equipped with testing materials including a test device, one sterile nasal swab and a pre-filled buffer tube with a cap and is priced at Rs 250 as an affordable single-pack, the company said.",
    categoryName: "Health",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data1.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data2.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data3.jpg"),
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health6Data4.jpg"),
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona,India",
    dislike: "0",
    subCat_id: "7",
    total_dislike: "",
    tagId: "1,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "39",
    userId: "1",
    newsId: "39",
    categoryId: "4",
    title:
        "Media reports alleging Centre hasn't placed any fresh order for COVID-19 vaccines incorrect: Health Ministry",
    date: "03-May-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/healthNews39.jpg",
    desc:
        "Apple has been listed as a client by a UK-based firm that manufactures photonics chips. Based on the work of the company, it is expected to supply glucose monitoring sensors to Apple for its Apple Watch in the coming years.\n\nHIGHLIGHTS\n\nRockley Photonics has listed Apple as one of its few large customers.\nThe company manufactures sensors that can monitor a person's blood using infrared light.\nThe firm has a \"supply and development agreement\" with Apple.\nApple might have a big feature lined up for the future iterations of the Apple Watch. As per a recent SEC filing, it seems that upcoming models of Apple Watch will have glucose monitoring capabilities on them.",
    categoryName: "Health",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health4Data1.jpg"),
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona,India",
    dislike: "0",
    subCat_id: "1",
    total_dislike: "",
    tagId: "1,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "50",
    userId: "1",
    newsId: "50",
    categoryId: "6",
    title:
        "New Zealand suspends ties with Myanmar after coup, puts travel ban on military leaders",
    date: "09-Feb-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/worldNews50.jpg",
    desc:
        "ew Zealand is suspending all high-level contact with Myanmar and imposing a travel ban on its military leaders following last week's coup, Prime Minister Jacinda Ardern said on Tuesday.\n\nNew Zealand will also ensure its aid programme will not include projects that are delivered with, or benefit, the military government, Ardern told a news conference.\n\n\"Our strong message is we will do what we can from here in New Zealand and one of the things we will do is suspend that high-level dialogue...and make sure any funding we put into Myanmar does not in any way support the military regime,\" Ardern said.\n\nNew Zealand's aid programme was worth about NZ\$42 million (\$30 million) between 2018 and 2021, she said.",
    categoryName: "World",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(otherImage: "assets/images/fullApps/modernNews/world6Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "51",
    userId: "1",
    newsId: "51",
    categoryId: "6",
    title:
        "Aung San Suu Kyi, other leaders detained as military declares one year emergency in Myanmar",
    date: "01-Feb-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/worldNews51.jpg",
    desc:
        "The intervention came after weeks of rising tensions between the military, which ruled the country for nearly five decades, and the civilian government over allegations of fraud in November's elections.\n\nMyanmar's military staged a coup on Monday, detaining de facto leader Aung San Suu Kyi and declaring it had taken control of the country for one year under a state of emergency.",
    categoryName: "World",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(otherImage: "assets/images/fullApps/modernNews/world7Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
];

List<News> bookmarkList = [
  News(
    id: "11",
    userId: "1",
    newsId: "11",
    categoryId: "5",
    title:
        "Ranveer gives Deepika a peck on the cheek, says ‘she’s my producer'. Watch",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews11.jpg",
    desc:
        "Deepika Padukone and Ranveer Singh were spotted at Mumbai airport early on Wednesday morning. Ranveer kissed Deepika, sending the paparazzi in a tizzy. \n\nDeepika Padukone and Ranveer Singh were spotted at the Mumbai airport early on Wednesday morning and sported contrasting travel looks. Ranveer not only gained attention for his quirky outfit but also indulged in a little PDA as he planted a kiss on Deepika's cheek while posing for the paparazzi. \n\nDeepika opted for a classic look in a black and white top and skirt paired with black boots and bag. She had her hair tied in a ponytail. Ranveer, meanwhile, was in an animal print tee and red velvet bell-bottoms paired with red framed glasses and and a black sling bag.\n\nRanveer got down from the car to get to the other side and opened the door for Deepika. As the two posed for photographs at the airport departure, he looked at Deepika and said “Meri producer hai (she's my producer).\" Deepika co-produces Ranveer's upcoming movie 83, which she also stars in.\n\n",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage:
              "assets/images/fullApps/modernNews/entertainment1Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "14",
    userId: "1",
    newsId: "14",
    categoryId: "3",
    title:
        "Manchester United's Premier League match against Brentford postponed due to Covid-19 outbreak within squad",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews14.jpg",
    desc:
        "Manchester United had reported a \"small number\" of cases discovered among first-team staff and players on Sunday, with the players who travelled to Norwich City for their Premier League clash on Saturday kept apart from those who had the virus.\n\nHIGHLIGHTS\nThe Premier League found a record 42 cases of COVID-19 among players and staff at various clubs\n\nThe 42 positive tests from over 3,800 individuals is more than the tally from the previous seven weeks combined\n\nBrentford said they welcomed the decision to postpone Tuesday's match\n\nManchester United's Premier League match at Brentford on Tuesday has been postponed due to a number of COVID-19 cases at the Old Trafford club, the league announced on Monday.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "FootBall",
    dislike: "0",
    subCat_id: "6",
    total_dislike: "",
    tagId: "6",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "15",
    userId: "1",
    newsId: "15",
    categoryId: "3",
    title:
        "Barcelona forward Sergio Aguero set to announcement retirement following heart evaluation",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/sportsNews15.jpg",
    desc:
        "Sergio Aguero was told by doctors to rest for three months after suffering chest pains during Barcelona's 1-1 draw against Alaves in the La Liga on October 30.\n\nHIGHLIGHTS\n\nSergio Aguero will make a statement on his future at the Nou Camp on Wednesday\nThe 33-year-old Argentina striker has been receiving treatment for a heart condition.\nAguero has made 5 appearances in all competitions for Barcelona so far since arriving from Man City\n\nBarcelona forward Sergio Aguero is likely to announce his retirement from football on December 15, reports in Spanish media suggested on Tuesday. Aguero's future as a professional footballer could be cut short after being diagnosed with a heart arrhythmia.\n\n",
    categoryName: "Sports",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "FootBall",
    dislike: "0",
    subCat_id: "5",
    total_dislike: "",
    tagId: "6",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "20",
    userId: "1",
    newsId: "20",
    categoryId: "1",
    title: "NIA arrests one more Afghan national in 3,000-kg drug haul case",
    date: "15-Dec-2021",
    contentType: "standard post",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/topNewsNews20.jpg",
    desc:
        "The National Investigation Agency (NIA) has arrested another Afghan national in connection with the 3,000-kg heroin seizure by the Directorate of Revenue Intelligence (DRI) at Mundra port in Gujarat in September.\n\nThe accused has been identified as Sobhan Aryanfar (28). The agency arrested him from Neb Sarai in south Delhi.\n\nAccording to the NIA, Aryanfar has been found to be involved in the conspiracy to transport narcotic drugs concealed in the import consignment of semi-processed talc stones, which had originated from Afghanistan.\n\nThe agency has registered the case under the Unlawful Activities (Prevention) Act and the relevant provisions of the Narcotic Drugs and Psychotropic Substances Act and the Indian Penal Code, on the basis of the findings of the DRI.\n\nThe NIA officials suspect that the same network had been used to smuggle in another consignment in the past.\n\nSome of the accused persons are said to be linked to a drug trafficking case registered earlier by the Special Cell of the Delhi Police.\n\nBased on the inputs, the NIA had conducted searches in different parts of the country, including in and around Delhi, in October. It collected samples of suspected drugs from a warehouse.\n\nEarlier, the DRI arrested 10 persons, including six Afghan nationals and an Uzbek woman, for their alleged involvement.\n\nThe DRI probe revealed that the contraband had been packed in Afghanistan and sent through Kandahar-based Hassan Hussain Limited. The consignment was declared as that of talc stones for export to Aashi Trading Company in Vijayawada, via Bandar Abbas port in Iran.\n\nThe drugs were meant to be brought to Delhi for further transportation and distribution.",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "21",
    userId: "21",
    newsId: "1",
    categoryId: "1",
    title:
        "Man from Nigeria with COVID-19 admitted to King Institute, Omicron suspected, says TN Health Minister",
    date: "15-Dec-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/health2Data4.jpg",
    desc:
        "A man who travelled to Tamil Nadu from Nigeria and six of his family members, with COVID-19, have been admitted to the King Institute of Preventive Medicine in Chennai, Health Minister Ma. Subramanian said in Tiruchi on Tuesday. The man had landed at the Chennai International Airport two days ago from Nigeria via Doha. He was randomly subjected to the RT-PCR test. The 47-year-old patient was detected with the ‘S’ gene drop out, one of the early indicators of the Omicron variant.\n\nFollowing this, his six other family members, were subjected to COVID-19 testing. They were also subsequently detected with the ‘S’ gene drop out. Since the preliminary analysis showed the possibility of the Omicron variant, they have been admitted to the King Institute. All of them are asymptomatic.They were under close surveillance, Mr. Subramanian told reporters after visiting the K.A.P. Viswanatham Medical College Hospital.\n\nMr. Subramanian said the samples had been sent to a laboratory in Bengaluru for genome sequencing tests. The results were expected on Tuesday evening or Wednesday. The State had so far sent samples of 29 other patients to Bengaluru to check for Omicron. Four of them had turned out to be cases of the Delta variant.\n\nThe Health Minister said that the State had 79 RT-PCR testing facilities. It had a capacity to screen 1.88 lakh patients a day. Twenty more RT-PCR machines had been procured for district headquarters hospitals and medical college hospitals to ramp up the testing facilities.\n\n",
    categoryName: "Top News",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona",
    dislike: "0",
    subCat_id: "4",
    total_dislike: "",
    tagId: "1",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "30",
    userId: "1",
    newsId: "30",
    categoryId: "5",
    title: "Bigg Boss 15: Jay Bhanushali to enter Salman Khan's reality show?",
    date: "01-Oct-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/entertainmentNews30.png",
    desc:
        "Another celebrity to join Salman Khan's show Bigg Boss 15 is TV actor Jay Bhanushali. Going by the latest reports, the actor has signed the dotted line and will enter the controversial show along with other contestants. \n\nWith just a few hours left for the grand premiere of the controversial reality show Bigg Boss 15, names of celebrities entering the house have been going viral on the internet. While celebrities like Umar Riaz, Tejasswi, Karan Kundrra, Sahil Shroff, and others have been confirmed, speculations about others are still going on. Another name that has popped on the internet to join Salman Khan's show is TV actor Jay Bhanushali. Going by the latest reports, the actor has signed the dotted line and will enter the show along with other contestants.\n\nJay Bhanushali has been seen on Bigg Boss many times before as a guest. He has not only entertained the fans with his perfect comic timing but also encouraged the contestants during his visits. A report in ETimes claims that Jay gave his nod a day before the show begins. It quoted a source saying, \"We were looking for a couple of popular TV actors and the deal with Jay materialised just a day before the contestants had to go inside the house.\"\n\nJay Bhanushali is a popular name on the small screen. Other than proving his acting mettle with high TRP daily soaps, the actor has been a part of reality shows as well. He has earlier participated in Jhalak Dikhhla Jaa, Kaun Jeetega Bollywood Ka Ticket, Iss Jungle Se Mujhe Bachao, Nachle Ve With Saroj Khan, Nach Baliye 5, and Fear Factor: Khatron Ke Khiladi 7.\n\nJay has been a part of TV shows like Kayamath, Kis Desh Mein Hai Meraa Dil, Geet - Hui Sabse Parayi and Kairi - Rishta Khatta Meetha.\n\nJay is married to actress Mahhi Vij. The duo had tied the knot in 2010 and their daughter Tara was born on August 21, 2019. They had also adopted their caretaker's kids, Khushi and Rajveer, in 2017.\n\nBesides Jay Bhanushali, Donal Bisht, Shamita Shetty and Nishant Bhat will also be locked in the 'BB15' house. Pratik Sehajpal is also the confirmed contestant from 'Bigg Boss OTT'. Others are Karan Kundra, Simba Nagpal, Sahil Shroff, Vidhi Pandya, Vishal Kotian.\n\nThe show's tagline is 'Sankat in Jungle, Phailaayega Dangal Pe Dangal'",
    categoryName: "Entertainment",
    counter: "",
    date_sent: "",
    imageDataList: [],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Celebrity,India",
    dislike: "0",
    subCat_id: "3",
    total_dislike: "",
    tagId: "3,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
  News(
    id: "39",
    userId: "1",
    newsId: "39",
    categoryId: "4",
    title:
        "Media reports alleging Centre hasn't placed any fresh order for COVID-19 vaccines incorrect: Health Ministry",
    date: "03-May-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/healthNews39.jpg",
    desc:
        "Apple has been listed as a client by a UK-based firm that manufactures photonics chips. Based on the work of the company, it is expected to supply glucose monitoring sensors to Apple for its Apple Watch in the coming years.\n\nHIGHLIGHTS\n\nRockley Photonics has listed Apple as one of its few large customers.\nThe company manufactures sensors that can monitor a person's blood using infrared light.\nThe firm has a \"supply and development agreement\" with Apple.\nApple might have a big feature lined up for the future iterations of the Apple Watch. As per a recent SEC filing, it seems that upcoming models of Apple Watch will have glucose monitoring capabilities on them.",
    categoryName: "Health",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(
          otherImage: "assets/images/fullApps/modernNews/health4Data1.jpg"),
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "Corona,India",
    dislike: "0",
    subCat_id: "1",
    total_dislike: "",
    tagId: "1,2",
    history: false,
    optionDataList: [],
    question: "",
    status: "0",
    type: "",
    from: 1,
  ),
  News(
    id: "50",
    userId: "1",
    newsId: "50",
    categoryId: "6",
    title:
        "New Zealand suspends ties with Myanmar after coup, puts travel ban on military leaders",
    date: "09-Feb-2021",
    contentType: "standard post	",
    contentValue: "",
    image: "assets/images/fullApps/modernNews/worldNews50.jpg",
    desc:
        "ew Zealand is suspending all high-level contact with Myanmar and imposing a travel ban on its military leaders following last week's coup, Prime Minister Jacinda Ardern said on Tuesday.\n\nNew Zealand will also ensure its aid programme will not include projects that are delivered with, or benefit, the military government, Ardern told a news conference.\n\n\"Our strong message is we will do what we can from here in New Zealand and one of the things we will do is suspend that high-level dialogue...and make sure any funding we put into Myanmar does not in any way support the military regime,\" Ardern said.\n\nNew Zealand's aid programme was worth about NZ\$42 million (\$30 million) between 2018 and 2021, she said.",
    categoryName: "World",
    counter: "",
    date_sent: "",
    imageDataList: [
      ImageData(otherImage: "assets/images/fullApps/modernNews/world6Data1.jpg")
    ],
    totalLikes: "5",
    like: "5",
    keyName: "",
    tagName: "",
    dislike: "0",
    subCat_id: "",
    total_dislike: "",
    tagId: "",
    history: false,
    optionDataList: [],
    question: "",
    status: "1",
    type: "",
    from: 1,
  ),
];
