import 'package:smartkit_pro/ui/fullApps/hotelBooking/model/galleryPhotos.dart';
import 'package:smartkit_pro/ui/fullApps/hotelBooking/model/hotelDetails.dart';
import 'package:smartkit_pro/ui/fullApps/hotelBooking/model/hotelFacilities.dart';
import 'package:smartkit_pro/ui/fullApps/hotelBooking/model/ratings.dart';

class HotelModel {
  String id,
      mainImage,
      name,
      price,
      city,
      address,
      description,
      ratings,
      totalReviewed;
  List<Rating> ratingList;
  List<HotelFacilities> facilities;
  List<HotelDetails> details;
  List<GalleryPhotos> galleryPhotos;

  HotelModel(
      {required this.id,
      required this.mainImage,
      required this.name,
      required this.price,
      required this.city,
      required this.address,
      required this.description,
      required this.ratings,
      required this.totalReviewed,
      required this.ratingList,
      required this.facilities,
      required this.details,
      required this.galleryPhotos});
}

List<HotelModel> hotelList = [
  HotelModel(
    id: 'hotelList_0',
    mainImage: "hotel_1.jpg",
    name: 'Retro Hotel',
    price: '29',
    city: 'Canada, Ottawa',
    address:
        '936 Margaret Junction, Lake Jenniferborough, United States, USA, 01916',
    description:
        "From the outside this house looks stylish. It has been built with wood covered in render and has tan stone decorations. Tall, large windows add to the overall style of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with a small kitchen and two bathrooms, it also has a small living room, four bedrooms, a spacious dining room, an office and a spacious garage.The building is shaped like a short U. The two extensions extend into stylish gardens to each side. second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a different style than the floor below.The roof is flat and is covered with slate shingles. Two small chimneys sit at the side of the house. Rows of small windows let in plenty of light to the rooms below the roof.The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot.",
    ratings: '4.8',
    totalReviewed: '1502',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'hotelList_1',
    mainImage: "hotel_2.jpg",
    name: 'Yesteryear Hotel',
    price: '69',
    city: 'China, Beijing',
    address: '4839 Feest Vista, South Emmittshire, USA, 74320-2348',
    description:
        "From the outside this house looks snug and comfortable. It has been built with white cedar wood and has white cedar wooden decorations. Tall, wide windows add to the overall style of the house and have been added to the house in a fairly symmetrical pattern.The house is equipped with a huge kitchen and one large bathroom, it also has a spacious living room, four bedrooms, a spacious dining room, a study and a large basement.The building is rectangular shaped. The house is fully surrounded by glass overhanging panels.The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.The roof is high, triangular, but one side is longer than the other and is covered with brown wood shingles. There are no chimneys. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.5',
    totalReviewed: '4801',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'hotelList_2',
    mainImage: "hotel_3.jpg",
    name: 'Refresh Resort',
    price: '25',
    city: 'France, Paris',
    address:
        '702 Bhooshit Cliff, North Ghanaanandfort, India,Indian Republic,Bharat,Hindustan, 233 774',
    description:
        "From the outside this house looks intimate and cozy. It has been built with walnut wood and has grey stone decorations. Tall, large windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a small basement.The building is shaped like a squared S. The two extensions extend into wooden sunscreens structures circling around half the house.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has roughly the same style as the floor below.The roof is high and v-shaped and is covered with stone slabs. Two small chimneys poke out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '5',
    totalReviewed: '5569',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'hotelList_3',
    mainImage: "hotel_4.jpg",
    name: 'Oceanside Resort',
    price: '89',
    city: 'Finland, Helsinki',
    address:
        '45353 Menon Course, Devdanview, India,Indian Republic,Bharat,Hindustan, 245 646',
    description:
        "From the outside this house looks grandiose. It has been built with tan stones and has white brick decorations. Tall, rectangular windows add to the overall look of the house and have been added to the house in a very asymmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, five bedrooms, a modest dining area, an office and a modest garage.The building is shaped like a short U. The two extensions are linked by a patio.The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has roughly the same style as the floor below.The roof is low and rounded and is covered with black roof tiles. One small chimney pokes out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4',
    totalReviewed: '6633',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'hotelList_4',
    mainImage: "hotel_5.jpg",
    name: 'Seacoast Hotel',
    price: '36',
    city: 'Kenya, Nairobi',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks gorgeous. It has been built with spruce wood and has tan stone decorations. Tall, rectangular windows brighten up the house and have been added to the house in a very symmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, four bedrooms, a cozy dining room, a multimedia room and a large storage room.The building is fairly rounded in shape. The house is half surrounded by a covered patio.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.The roof is low and triangular and is covered with brown ceramic tiles. One small chimney sits at the side of the house. Several long, thin windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '3.9',
    totalReviewed: '6969',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'hotelList_5',
    mainImage: "hotel_6.jpg",
    name: 'Crimson Jewel Hotel',
    price: '86',
    city: 'Japan, Tokyo',
    address: '4467 Homenick Stravenue, Janesville, USA, 25295-4823',
    description:
        "From the outside this house looks very elegant. It has been built with white pine wood and has spruce wooden decorations. Tall, squared windows brighten up the house and have been added to the house in a very asymmetric way.The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, three bedrooms, a small dining room and a spacious basement.The building is rectangular shaped. The house is half surrounded by overgrown wooden overhanging panels.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a very different style than the floor below.The roof is low and slanted to one side and is covered with brown roof tiles. One small chimney pokes out the center of the roof. There are no windows on the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4.8',
    totalReviewed: '8856',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'hotelList_6',
    mainImage: "hotel_7.jpg",
    name: 'Crimson Jewel Hotel',
    price: '23',
    city: 'Canada, Ottawa',
    address: '24615 Mayra Trail, Lake Carolyneside, USA, 40585',
    description:
        "From the outside this house looks very elegant. It has been built with red pine wood and has sandstone decorations. Tall, squared windows let in plenty of light and have been added to the house in a very symmetric way.The house is equipped with a huge kitchen and one modern bathroom, it also has a generous living room, five bedrooms, a modest dining area, a playroom and a modest garage.The building is rectangular shaped. The house is fully surrounded by cloth sunscreens.The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor has roughly the same style as the floor below.The roof is low and triangular and is covered with overlapping roof tiles. Two small chimneys poke out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.8',
    totalReviewed: '1256',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'hotelList_7',
    mainImage: "hotel_8.jpg",
    name: 'Secret Court Hotel',
    price: '29',
    city: 'China, Beijing',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks magnificent. It has been built with walnut wood and has grey brick decorations. Large, octagon windows add to the overall style of the house and have been added to the house in a very symmetric way.The house is equipped with a large kitchen and two bathrooms, it also has a small living room, three bedrooms, a roomy dining room, a library and a large basement.The building is shaped like a squared S. The two extensions extend into glass overhanging panels circling around half the house.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.The roof is high and slanted to one side and is covered with grey roof tiles. Two large chimneys sit at the side of the house. There are no windows on the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '4.5',
    totalReviewed: '1265',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  )
];

List<HotelModel> recommendedHotelList = [
  HotelModel(
    id: 'recommendedHotelList_0',
    mainImage: "hotel_1.jpg",
    name: 'Retro Hotel',
    price: '29',
    city: 'Canada, Ottawa',
    address:
        '936 Margaret Junction, Lake Jenniferborough, United States, USA, 01916',
    description:
        "From the outside this house looks stylish. It has been built with wood covered in render and has tan stone decorations. Tall, large windows add to the overall style of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with a small kitchen and two bathrooms, it also has a small living room, four bedrooms, a spacious dining room, an office and a spacious garage.The building is shaped like a short U. The two extensions extend into stylish gardens to each side. second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a different style than the floor below.The roof is flat and is covered with slate shingles. Two small chimneys sit at the side of the house. Rows of small windows let in plenty of light to the rooms below the roof.The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot.",
    ratings: '4.8',
    totalReviewed: '1502',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'recommendedHotelList_1',
    mainImage: "hotel_2.jpg",
    name: 'Yesteryear Hotel',
    price: '69',
    city: 'China, Beijing',
    address: '4839 Feest Vista, South Emmittshire, USA, 74320-2348',
    description:
        "From the outside this house looks snug and comfortable. It has been built with white cedar wood and has white cedar wooden decorations. Tall, wide windows add to the overall style of the house and have been added to the house in a fairly symmetrical pattern.The house is equipped with a huge kitchen and one large bathroom, it also has a spacious living room, four bedrooms, a spacious dining room, a study and a large basement.The building is rectangular shaped. The house is fully surrounded by glass overhanging panels.The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.The roof is high, triangular, but one side is longer than the other and is covered with brown wood shingles. There are no chimneys. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.5',
    totalReviewed: '4801',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'recommendedHotelList_2',
    mainImage: "hotel_3.jpg",
    name: 'Refresh Resort',
    price: '25',
    city: 'France, Paris',
    address:
        '702 Bhooshit Cliff, North Ghanaanandfort, India,Indian Republic,Bharat,Hindustan, 233 774',
    description:
        "From the outside this house looks intimate and cozy. It has been built with walnut wood and has grey stone decorations. Tall, large windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a small basement.The building is shaped like a squared S. The two extensions extend into wooden sunscreens structures circling around half the house.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has roughly the same style as the floor below.The roof is high and v-shaped and is covered with stone slabs. Two small chimneys poke out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '5',
    totalReviewed: '5569',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'recommendedHotelList_3',
    mainImage: "hotel_4.jpg",
    name: 'Oceanside Resort',
    price: '89',
    city: 'Finland, Helsinki',
    address:
        '45353 Menon Course, Devdanview, India,Indian Republic,Bharat,Hindustan, 245 646',
    description:
        "From the outside this house looks grandiose. It has been built with tan stones and has white brick decorations. Tall, rectangular windows add to the overall look of the house and have been added to the house in a very asymmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, five bedrooms, a modest dining area, an office and a modest garage.The building is shaped like a short U. The two extensions are linked by a patio.The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has roughly the same style as the floor below.The roof is low and rounded and is covered with black roof tiles. One small chimney pokes out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4',
    totalReviewed: '6633',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'recommendedHotelList_4',
    mainImage: "hotel_5.jpg",
    name: 'Seacoast Hotel',
    price: '36',
    city: 'Kenya, Nairobi',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks gorgeous. It has been built with spruce wood and has tan stone decorations. Tall, rectangular windows brighten up the house and have been added to the house in a very symmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, four bedrooms, a cozy dining room, a multimedia room and a large storage room.The building is fairly rounded in shape. The house is half surrounded by a covered patio.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.The roof is low and triangular and is covered with brown ceramic tiles. One small chimney sits at the side of the house. Several long, thin windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '3.9',
    totalReviewed: '6969',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'recommendedHotelList_5',
    mainImage: "hotel_6.jpg",
    name: 'Crimson Jewel Hotel',
    price: '86',
    city: 'Japan, Tokyo',
    address: '4467 Homenick Stravenue, Janesville, USA, 25295-4823',
    description:
        "From the outside this house looks very elegant. It has been built with white pine wood and has spruce wooden decorations. Tall, squared windows brighten up the house and have been added to the house in a very asymmetric way.The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, three bedrooms, a small dining room and a spacious basement.The building is rectangular shaped. The house is half surrounded by overgrown wooden overhanging panels.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a very different style than the floor below.The roof is low and slanted to one side and is covered with brown roof tiles. One small chimney pokes out the center of the roof. There are no windows on the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4.8',
    totalReviewed: '8856',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'recommendedHotelList_6',
    mainImage: "hotel_7.jpg",
    name: 'Crimson Jewel Hotel',
    price: '23',
    city: 'Canada, Ottawa',
    address: '24615 Mayra Trail, Lake Carolyneside, USA, 40585',
    description:
        "From the outside this house looks very elegant. It has been built with red pine wood and has sandstone decorations. Tall, squared windows let in plenty of light and have been added to the house in a very symmetric way.The house is equipped with a huge kitchen and one modern bathroom, it also has a generous living room, five bedrooms, a modest dining area, a playroom and a modest garage.The building is rectangular shaped. The house is fully surrounded by cloth sunscreens.The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor has roughly the same style as the floor below.The roof is low and triangular and is covered with overlapping roof tiles. Two small chimneys poke out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.8',
    totalReviewed: '1256',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'recommendedHotelList_7',
    mainImage: "hotel_8.jpg",
    name: 'Secret Court Hotel',
    price: '29',
    city: 'China, Beijing',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks magnificent. It has been built with walnut wood and has grey brick decorations. Large, octagon windows add to the overall style of the house and have been added to the house in a very symmetric way.The house is equipped with a large kitchen and two bathrooms, it also has a small living room, three bedrooms, a roomy dining room, a library and a large basement.The building is shaped like a squared S. The two extensions extend into glass overhanging panels circling around half the house.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.The roof is high and slanted to one side and is covered with grey roof tiles. Two large chimneys sit at the side of the house. There are no windows on the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '4.5',
    totalReviewed: '1265',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  )
];

List<HotelModel> topRatedHotelList = [
  HotelModel(
    id: 'topRatedHotelList_0',
    mainImage: "hotel_1.jpg",
    name: 'Retro Hotel',
    price: '29',
    city: 'Canada, Ottawa',
    address:
        '936 Margaret Junction, Lake Jenniferborough, United States, USA, 01916',
    description:
        "From the outside this house looks stylish. It has been built with wood covered in render and has tan stone decorations. Tall, large windows add to the overall style of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with a small kitchen and two bathrooms, it also has a small living room, four bedrooms, a spacious dining room, an office and a spacious garage.The building is shaped like a short U. The two extensions extend into stylish gardens to each side. second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a different style than the floor below.The roof is flat and is covered with slate shingles. Two small chimneys sit at the side of the house. Rows of small windows let in plenty of light to the rooms below the roof.The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot.",
    ratings: '4.8',
    totalReviewed: '1502',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topRatedHotelList_1',
    mainImage: "hotel_2.jpg",
    name: 'Yesteryear Hotel',
    price: '69',
    city: 'China, Beijing',
    address: '4839 Feest Vista, South Emmittshire, USA, 74320-2348',
    description:
        "From the outside this house looks snug and comfortable. It has been built with white cedar wood and has white cedar wooden decorations. Tall, wide windows add to the overall style of the house and have been added to the house in a fairly symmetrical pattern.The house is equipped with a huge kitchen and one large bathroom, it also has a spacious living room, four bedrooms, a spacious dining room, a study and a large basement.The building is rectangular shaped. The house is fully surrounded by glass overhanging panels.The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.The roof is high, triangular, but one side is longer than the other and is covered with brown wood shingles. There are no chimneys. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.5',
    totalReviewed: '4801',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topRatedHotelList_2',
    mainImage: "hotel_3.jpg",
    name: 'Refresh Resort',
    price: '25',
    city: 'France, Paris',
    address:
        '702 Bhooshit Cliff, North Ghanaanandfort, India,Indian Republic,Bharat,Hindustan, 233 774',
    description:
        "From the outside this house looks intimate and cozy. It has been built with walnut wood and has grey stone decorations. Tall, large windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a small basement.The building is shaped like a squared S. The two extensions extend into wooden sunscreens structures circling around half the house.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has roughly the same style as the floor below.The roof is high and v-shaped and is covered with stone slabs. Two small chimneys poke out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '5',
    totalReviewed: '5569',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topRatedHotelList_3',
    mainImage: "hotel_4.jpg",
    name: 'Oceanside Resort',
    price: '89',
    city: 'Finland, Helsinki',
    address:
        '45353 Menon Course, Devdanview, India,Indian Republic,Bharat,Hindustan, 245 646',
    description:
        "From the outside this house looks grandiose. It has been built with tan stones and has white brick decorations. Tall, rectangular windows add to the overall look of the house and have been added to the house in a very asymmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, five bedrooms, a modest dining area, an office and a modest garage.The building is shaped like a short U. The two extensions are linked by a patio.The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has roughly the same style as the floor below.The roof is low and rounded and is covered with black roof tiles. One small chimney pokes out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4',
    totalReviewed: '6633',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topRatedHotelList_4',
    mainImage: "hotel_5.jpg",
    name: 'Seacoast Hotel',
    price: '36',
    city: 'Kenya, Nairobi',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks gorgeous. It has been built with spruce wood and has tan stone decorations. Tall, rectangular windows brighten up the house and have been added to the house in a very symmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, four bedrooms, a cozy dining room, a multimedia room and a large storage room.The building is fairly rounded in shape. The house is half surrounded by a covered patio.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.The roof is low and triangular and is covered with brown ceramic tiles. One small chimney sits at the side of the house. Several long, thin windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '3.9',
    totalReviewed: '6969',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topRatedHotelList_5',
    mainImage: "hotel_6.jpg",
    name: 'Crimson Jewel Hotel',
    price: '86',
    city: 'Japan, Tokyo',
    address: '4467 Homenick Stravenue, Janesville, USA, 25295-4823',
    description:
        "From the outside this house looks very elegant. It has been built with white pine wood and has spruce wooden decorations. Tall, squared windows brighten up the house and have been added to the house in a very asymmetric way.The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, three bedrooms, a small dining room and a spacious basement.The building is rectangular shaped. The house is half surrounded by overgrown wooden overhanging panels.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a very different style than the floor below.The roof is low and slanted to one side and is covered with brown roof tiles. One small chimney pokes out the center of the roof. There are no windows on the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4.8',
    totalReviewed: '8856',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topRatedHotelList_6',
    mainImage: "hotel_7.jpg",
    name: 'Crimson Jewel Hotel',
    price: '23',
    city: 'Canada, Ottawa',
    address: '24615 Mayra Trail, Lake Carolyneside, USA, 40585',
    description:
        "From the outside this house looks very elegant. It has been built with red pine wood and has sandstone decorations. Tall, squared windows let in plenty of light and have been added to the house in a very symmetric way.The house is equipped with a huge kitchen and one modern bathroom, it also has a generous living room, five bedrooms, a modest dining area, a playroom and a modest garage.The building is rectangular shaped. The house is fully surrounded by cloth sunscreens.The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor has roughly the same style as the floor below.The roof is low and triangular and is covered with overlapping roof tiles. Two small chimneys poke out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.8',
    totalReviewed: '1256',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topRatedHotelList_7',
    mainImage: "hotel_8.jpg",
    name: 'Secret Court Hotel',
    price: '29',
    city: 'China, Beijing',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks magnificent. It has been built with walnut wood and has grey brick decorations. Large, octagon windows add to the overall style of the house and have been added to the house in a very symmetric way.The house is equipped with a large kitchen and two bathrooms, it also has a small living room, three bedrooms, a roomy dining room, a library and a large basement.The building is shaped like a squared S. The two extensions extend into glass overhanging panels circling around half the house.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.The roof is high and slanted to one side and is covered with grey roof tiles. Two large chimneys sit at the side of the house. There are no windows on the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '4.5',
    totalReviewed: '1265',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  )
];

List<HotelModel> bookMarkedHotelList = [
  HotelModel(
    id: 'bookMarkedHotelList_0',
    mainImage: "hotel_1.jpg",
    name: 'Retro Hotel',
    price: '29',
    city: 'Canada, Ottawa',
    address:
        '936 Margaret Junction, Lake Jenniferborough, United States, USA, 01916',
    description:
        "From the outside this house looks stylish. It has been built with wood covered in render and has tan stone decorations. Tall, large windows add to the overall style of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with a small kitchen and two bathrooms, it also has a small living room, four bedrooms, a spacious dining room, an office and a spacious garage.The building is shaped like a short U. The two extensions extend into stylish gardens to each side. second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a different style than the floor below.The roof is flat and is covered with slate shingles. Two small chimneys sit at the side of the house. Rows of small windows let in plenty of light to the rooms below the roof.The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot.",
    ratings: '4.8',
    totalReviewed: '1502',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'bookMarkedHotelList_1',
    mainImage: "hotel_2.jpg",
    name: 'Yesteryear Hotel',
    price: '69',
    city: 'China, Beijing',
    address: '4839 Feest Vista, South Emmittshire, USA, 74320-2348',
    description:
        "From the outside this house looks snug and comfortable. It has been built with white cedar wood and has white cedar wooden decorations. Tall, wide windows add to the overall style of the house and have been added to the house in a fairly symmetrical pattern.The house is equipped with a huge kitchen and one large bathroom, it also has a spacious living room, four bedrooms, a spacious dining room, a study and a large basement.The building is rectangular shaped. The house is fully surrounded by glass overhanging panels.The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.The roof is high, triangular, but one side is longer than the other and is covered with brown wood shingles. There are no chimneys. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.5',
    totalReviewed: '4801',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'bookMarkedHotelList_2',
    mainImage: "hotel_3.jpg",
    name: 'Refresh Resort',
    price: '25',
    city: 'France, Paris',
    address:
        '702 Bhooshit Cliff, North Ghanaanandfort, India,Indian Republic,Bharat,Hindustan, 233 774',
    description:
        "From the outside this house looks intimate and cozy. It has been built with walnut wood and has grey stone decorations. Tall, large windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a small basement.The building is shaped like a squared S. The two extensions extend into wooden sunscreens structures circling around half the house.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has roughly the same style as the floor below.The roof is high and v-shaped and is covered with stone slabs. Two small chimneys poke out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '5',
    totalReviewed: '5569',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'bookMarkedHotelList_3',
    mainImage: "hotel_4.jpg",
    name: 'Oceanside Resort',
    price: '89',
    city: 'Finland, Helsinki',
    address:
        '45353 Menon Course, Devdanview, India,Indian Republic,Bharat,Hindustan, 245 646',
    description:
        "From the outside this house looks grandiose. It has been built with tan stones and has white brick decorations. Tall, rectangular windows add to the overall look of the house and have been added to the house in a very asymmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, five bedrooms, a modest dining area, an office and a modest garage.The building is shaped like a short U. The two extensions are linked by a patio.The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has roughly the same style as the floor below.The roof is low and rounded and is covered with black roof tiles. One small chimney pokes out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4',
    totalReviewed: '6633',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'bookMarkedHotelList_4',
    mainImage: "hotel_5.jpg",
    name: 'Seacoast Hotel',
    price: '36',
    city: 'Kenya, Nairobi',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks gorgeous. It has been built with spruce wood and has tan stone decorations. Tall, rectangular windows brighten up the house and have been added to the house in a very symmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, four bedrooms, a cozy dining room, a multimedia room and a large storage room.The building is fairly rounded in shape. The house is half surrounded by a covered patio.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.The roof is low and triangular and is covered with brown ceramic tiles. One small chimney sits at the side of the house. Several long, thin windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '3.9',
    totalReviewed: '6969',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'bookMarkedHotelList_5',
    mainImage: "hotel_6.jpg",
    name: 'Crimson Jewel Hotel',
    price: '86',
    city: 'Japan, Tokyo',
    address: '4467 Homenick Stravenue, Janesville, USA, 25295-4823',
    description:
        "From the outside this house looks very elegant. It has been built with white pine wood and has spruce wooden decorations. Tall, squared windows brighten up the house and have been added to the house in a very asymmetric way.The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, three bedrooms, a small dining room and a spacious basement.The building is rectangular shaped. The house is half surrounded by overgrown wooden overhanging panels.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a very different style than the floor below.The roof is low and slanted to one side and is covered with brown roof tiles. One small chimney pokes out the center of the roof. There are no windows on the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4.8',
    totalReviewed: '8856',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'bookMarkedHotelList_6',
    mainImage: "hotel_7.jpg",
    name: 'Crimson Jewel Hotel',
    price: '23',
    city: 'Canada, Ottawa',
    address: '24615 Mayra Trail, Lake Carolyneside, USA, 40585',
    description:
        "From the outside this house looks very elegant. It has been built with red pine wood and has sandstone decorations. Tall, squared windows let in plenty of light and have been added to the house in a very symmetric way.The house is equipped with a huge kitchen and one modern bathroom, it also has a generous living room, five bedrooms, a modest dining area, a playroom and a modest garage.The building is rectangular shaped. The house is fully surrounded by cloth sunscreens.The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor has roughly the same style as the floor below.The roof is low and triangular and is covered with overlapping roof tiles. Two small chimneys poke out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.8',
    totalReviewed: '1256',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'bookMarkedHotelList_7',
    mainImage: "hotel_8.jpg",
    name: 'Secret Court Hotel',
    price: '29',
    city: 'China, Beijing',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks magnificent. It has been built with walnut wood and has grey brick decorations. Large, octagon windows add to the overall style of the house and have been added to the house in a very symmetric way.The house is equipped with a large kitchen and two bathrooms, it also has a small living room, three bedrooms, a roomy dining room, a library and a large basement.The building is shaped like a squared S. The two extensions extend into glass overhanging panels circling around half the house.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.The roof is high and slanted to one side and is covered with grey roof tiles. Two large chimneys sit at the side of the house. There are no windows on the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '4.5',
    totalReviewed: '1265',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  )
];

List<HotelModel> popularHotelList = [
  HotelModel(
    id: 'popularHotelList_0',
    mainImage: "hotel_1.jpg",
    name: 'Retro Hotel',
    price: '29',
    city: 'Canada, Ottawa',
    address:
        '936 Margaret Junction, Lake Jenniferborough, United States, USA, 01916',
    description:
        "From the outside this house looks stylish. It has been built with wood covered in render and has tan stone decorations. Tall, large windows add to the overall style of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with a small kitchen and two bathrooms, it also has a small living room, four bedrooms, a spacious dining room, an office and a spacious garage.The building is shaped like a short U. The two extensions extend into stylish gardens to each side. second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a different style than the floor below.The roof is flat and is covered with slate shingles. Two small chimneys sit at the side of the house. Rows of small windows let in plenty of light to the rooms below the roof.The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot.",
    ratings: '4.8',
    totalReviewed: '1502',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'popularHotelList_1',
    mainImage: "hotel_2.jpg",
    name: 'Yesteryear Hotel',
    price: '69',
    city: 'China, Beijing',
    address: '4839 Feest Vista, South Emmittshire, USA, 74320-2348',
    description:
        "From the outside this house looks snug and comfortable. It has been built with white cedar wood and has white cedar wooden decorations. Tall, wide windows add to the overall style of the house and have been added to the house in a fairly symmetrical pattern.The house is equipped with a huge kitchen and one large bathroom, it also has a spacious living room, four bedrooms, a spacious dining room, a study and a large basement.The building is rectangular shaped. The house is fully surrounded by glass overhanging panels.The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.The roof is high, triangular, but one side is longer than the other and is covered with brown wood shingles. There are no chimneys. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.5',
    totalReviewed: '4801',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'popularHotelList_2',
    mainImage: "hotel_3.jpg",
    name: 'Refresh Resort',
    price: '25',
    city: 'France, Paris',
    address:
        '702 Bhooshit Cliff, North Ghanaanandfort, India,Indian Republic,Bharat,Hindustan, 233 774',
    description:
        "From the outside this house looks intimate and cozy. It has been built with walnut wood and has grey stone decorations. Tall, large windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a small basement.The building is shaped like a squared S. The two extensions extend into wooden sunscreens structures circling around half the house.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has roughly the same style as the floor below.The roof is high and v-shaped and is covered with stone slabs. Two small chimneys poke out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '5',
    totalReviewed: '5569',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'popularHotelList_3',
    mainImage: "hotel_4.jpg",
    name: 'Oceanside Resort',
    price: '89',
    city: 'Finland, Helsinki',
    address:
        '45353 Menon Course, Devdanview, India,Indian Republic,Bharat,Hindustan, 245 646',
    description:
        "From the outside this house looks grandiose. It has been built with tan stones and has white brick decorations. Tall, rectangular windows add to the overall look of the house and have been added to the house in a very asymmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, five bedrooms, a modest dining area, an office and a modest garage.The building is shaped like a short U. The two extensions are linked by a patio.The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has roughly the same style as the floor below.The roof is low and rounded and is covered with black roof tiles. One small chimney pokes out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4',
    totalReviewed: '6633',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'popularHotelList_4',
    mainImage: "hotel_5.jpg",
    name: 'Seacoast Hotel',
    price: '36',
    city: 'Kenya, Nairobi',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks gorgeous. It has been built with spruce wood and has tan stone decorations. Tall, rectangular windows brighten up the house and have been added to the house in a very symmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, four bedrooms, a cozy dining room, a multimedia room and a large storage room.The building is fairly rounded in shape. The house is half surrounded by a covered patio.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.The roof is low and triangular and is covered with brown ceramic tiles. One small chimney sits at the side of the house. Several long, thin windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '3.9',
    totalReviewed: '6969',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'popularHotelList_5',
    mainImage: "hotel_6.jpg",
    name: 'Crimson Jewel Hotel',
    price: '86',
    city: 'Japan, Tokyo',
    address: '4467 Homenick Stravenue, Janesville, USA, 25295-4823',
    description:
        "From the outside this house looks very elegant. It has been built with white pine wood and has spruce wooden decorations. Tall, squared windows brighten up the house and have been added to the house in a very asymmetric way.The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, three bedrooms, a small dining room and a spacious basement.The building is rectangular shaped. The house is half surrounded by overgrown wooden overhanging panels.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a very different style than the floor below.The roof is low and slanted to one side and is covered with brown roof tiles. One small chimney pokes out the center of the roof. There are no windows on the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4.8',
    totalReviewed: '8856',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'popularHotelList_6',
    mainImage: "hotel_7.jpg",
    name: 'Crimson Jewel Hotel',
    price: '23',
    city: 'Canada, Ottawa',
    address: '24615 Mayra Trail, Lake Carolyneside, USA, 40585',
    description:
        "From the outside this house looks very elegant. It has been built with red pine wood and has sandstone decorations. Tall, squared windows let in plenty of light and have been added to the house in a very symmetric way.The house is equipped with a huge kitchen and one modern bathroom, it also has a generous living room, five bedrooms, a modest dining area, a playroom and a modest garage.The building is rectangular shaped. The house is fully surrounded by cloth sunscreens.The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor has roughly the same style as the floor below.The roof is low and triangular and is covered with overlapping roof tiles. Two small chimneys poke out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.8',
    totalReviewed: '1256',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'popularHotelList_7',
    mainImage: "hotel_8.jpg",
    name: 'Secret Court Hotel',
    price: '29',
    city: 'China, Beijing',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks magnificent. It has been built with walnut wood and has grey brick decorations. Large, octagon windows add to the overall style of the house and have been added to the house in a very symmetric way.The house is equipped with a large kitchen and two bathrooms, it also has a small living room, three bedrooms, a roomy dining room, a library and a large basement.The building is shaped like a squared S. The two extensions extend into glass overhanging panels circling around half the house.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.The roof is high and slanted to one side and is covered with grey roof tiles. Two large chimneys sit at the side of the house. There are no windows on the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '4.5',
    totalReviewed: '1265',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  )
];

List<HotelModel> trendingHotelList = [
  HotelModel(
    id: 'trendingHotelList_0',
    mainImage: "hotel_1.jpg",
    name: 'Retro Hotel',
    price: '29',
    city: 'Canada, Ottawa',
    address:
        '936 Margaret Junction, Lake Jenniferborough, United States, USA, 01916',
    description:
        "From the outside this house looks stylish. It has been built with wood covered in render and has tan stone decorations. Tall, large windows add to the overall style of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with a small kitchen and two bathrooms, it also has a small living room, four bedrooms, a spacious dining room, an office and a spacious garage.The building is shaped like a short U. The two extensions extend into stylish gardens to each side. second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a different style than the floor below.The roof is flat and is covered with slate shingles. Two small chimneys sit at the side of the house. Rows of small windows let in plenty of light to the rooms below the roof.The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot.",
    ratings: '4.8',
    totalReviewed: '1502',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'trendingHotelList_1',
    mainImage: "hotel_2.jpg",
    name: 'Yesteryear Hotel',
    price: '69',
    city: 'China, Beijing',
    address: '4839 Feest Vista, South Emmittshire, USA, 74320-2348',
    description:
        "From the outside this house looks snug and comfortable. It has been built with white cedar wood and has white cedar wooden decorations. Tall, wide windows add to the overall style of the house and have been added to the house in a fairly symmetrical pattern.The house is equipped with a huge kitchen and one large bathroom, it also has a spacious living room, four bedrooms, a spacious dining room, a study and a large basement.The building is rectangular shaped. The house is fully surrounded by glass overhanging panels.The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.The roof is high, triangular, but one side is longer than the other and is covered with brown wood shingles. There are no chimneys. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.5',
    totalReviewed: '4801',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'trendingHotelList_2',
    mainImage: "hotel_3.jpg",
    name: 'Refresh Resort',
    price: '25',
    city: 'France, Paris',
    address:
        '702 Bhooshit Cliff, North Ghanaanandfort, India,Indian Republic,Bharat,Hindustan, 233 774',
    description:
        "From the outside this house looks intimate and cozy. It has been built with walnut wood and has grey stone decorations. Tall, large windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a small basement.The building is shaped like a squared S. The two extensions extend into wooden sunscreens structures circling around half the house.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has roughly the same style as the floor below.The roof is high and v-shaped and is covered with stone slabs. Two small chimneys poke out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '5',
    totalReviewed: '5569',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'trendingHotelList_3',
    mainImage: "hotel_4.jpg",
    name: 'Oceanside Resort',
    price: '89',
    city: 'Finland, Helsinki',
    address:
        '45353 Menon Course, Devdanview, India,Indian Republic,Bharat,Hindustan, 245 646',
    description:
        "From the outside this house looks grandiose. It has been built with tan stones and has white brick decorations. Tall, rectangular windows add to the overall look of the house and have been added to the house in a very asymmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, five bedrooms, a modest dining area, an office and a modest garage.The building is shaped like a short U. The two extensions are linked by a patio.The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has roughly the same style as the floor below.The roof is low and rounded and is covered with black roof tiles. One small chimney pokes out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4',
    totalReviewed: '6633',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'trendingHotelList_4',
    mainImage: "hotel_5.jpg",
    name: 'Seacoast Hotel',
    price: '36',
    city: 'Kenya, Nairobi',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks gorgeous. It has been built with spruce wood and has tan stone decorations. Tall, rectangular windows brighten up the house and have been added to the house in a very symmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, four bedrooms, a cozy dining room, a multimedia room and a large storage room.The building is fairly rounded in shape. The house is half surrounded by a covered patio.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.The roof is low and triangular and is covered with brown ceramic tiles. One small chimney sits at the side of the house. Several long, thin windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '3.9',
    totalReviewed: '6969',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'trendingHotelList_5',
    mainImage: "hotel_6.jpg",
    name: 'Crimson Jewel Hotel',
    price: '86',
    city: 'Japan, Tokyo',
    address: '4467 Homenick Stravenue, Janesville, USA, 25295-4823',
    description:
        "From the outside this house looks very elegant. It has been built with white pine wood and has spruce wooden decorations. Tall, squared windows brighten up the house and have been added to the house in a very asymmetric way.The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, three bedrooms, a small dining room and a spacious basement.The building is rectangular shaped. The house is half surrounded by overgrown wooden overhanging panels.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a very different style than the floor below.The roof is low and slanted to one side and is covered with brown roof tiles. One small chimney pokes out the center of the roof. There are no windows on the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4.8',
    totalReviewed: '8856',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'trendingHotelList_6',
    mainImage: "hotel_7.jpg",
    name: 'Crimson Jewel Hotel',
    price: '23',
    city: 'Canada, Ottawa',
    address: '24615 Mayra Trail, Lake Carolyneside, USA, 40585',
    description:
        "From the outside this house looks very elegant. It has been built with red pine wood and has sandstone decorations. Tall, squared windows let in plenty of light and have been added to the house in a very symmetric way.The house is equipped with a huge kitchen and one modern bathroom, it also has a generous living room, five bedrooms, a modest dining area, a playroom and a modest garage.The building is rectangular shaped. The house is fully surrounded by cloth sunscreens.The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor has roughly the same style as the floor below.The roof is low and triangular and is covered with overlapping roof tiles. Two small chimneys poke out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.8',
    totalReviewed: '1256',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'trendingHotelList_7',
    mainImage: "hotel_8.jpg",
    name: 'Secret Court Hotel',
    price: '29',
    city: 'China, Beijing',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks magnificent. It has been built with walnut wood and has grey brick decorations. Large, octagon windows add to the overall style of the house and have been added to the house in a very symmetric way.The house is equipped with a large kitchen and two bathrooms, it also has a small living room, three bedrooms, a roomy dining room, a library and a large basement.The building is shaped like a squared S. The two extensions extend into glass overhanging panels circling around half the house.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.The roof is high and slanted to one side and is covered with grey roof tiles. Two large chimneys sit at the side of the house. There are no windows on the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '4.5',
    totalReviewed: '1265',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  )
];

List<HotelModel> topCheapestHotelList = [
  HotelModel(
    id: 'topCheapestHotelList_0',
    mainImage: "hotel_1.jpg",
    name: 'Retro Hotel',
    price: '29',
    city: 'Canada, Ottawa',
    address:
        '936 Margaret Junction, Lake Jenniferborough, United States, USA, 01916',
    description:
        "From the outside this house looks stylish. It has been built with wood covered in render and has tan stone decorations. Tall, large windows add to the overall style of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with a small kitchen and two bathrooms, it also has a small living room, four bedrooms, a spacious dining room, an office and a spacious garage.The building is shaped like a short U. The two extensions extend into stylish gardens to each side. second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a different style than the floor below.The roof is flat and is covered with slate shingles. Two small chimneys sit at the side of the house. Rows of small windows let in plenty of light to the rooms below the roof.The house itself is surrounded by grass, a huge tree in the center and bushes on the borders of the plot.",
    ratings: '4.8',
    totalReviewed: '1502',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topCheapestHotelList_1',
    mainImage: "hotel_2.jpg",
    name: 'Yesteryear Hotel',
    price: '69',
    city: 'China, Beijing',
    address: '4839 Feest Vista, South Emmittshire, USA, 74320-2348',
    description:
        "From the outside this house looks snug and comfortable. It has been built with white cedar wood and has white cedar wooden decorations. Tall, wide windows add to the overall style of the house and have been added to the house in a fairly symmetrical pattern.The house is equipped with a huge kitchen and one large bathroom, it also has a spacious living room, four bedrooms, a spacious dining room, a study and a large basement.The building is rectangular shaped. The house is fully surrounded by glass overhanging panels.The second floor is bigger than the first, which creates a stylish overhang around the entire house. This floor follows the same style as the floor below.The roof is high, triangular, but one side is longer than the other and is covered with brown wood shingles. There are no chimneys. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.5',
    totalReviewed: '4801',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topCheapestHotelList_2',
    mainImage: "hotel_3.jpg",
    name: 'Refresh Resort',
    price: '25',
    city: 'France, Paris',
    address:
        '702 Bhooshit Cliff, North Ghanaanandfort, India,Indian Republic,Bharat,Hindustan, 233 774',
    description:
        "From the outside this house looks intimate and cozy. It has been built with walnut wood and has grey stone decorations. Tall, large windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern.The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, two bedrooms, a small dining room and a small basement.The building is shaped like a squared S. The two extensions extend into wooden sunscreens structures circling around half the house.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor has roughly the same style as the floor below.The roof is high and v-shaped and is covered with stone slabs. Two small chimneys poke out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '5',
    totalReviewed: '5569',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topCheapestHotelList_3',
    mainImage: "hotel_4.jpg",
    name: 'Oceanside Resort',
    price: '89',
    city: 'Finland, Helsinki',
    address:
        '45353 Menon Course, Devdanview, India,Indian Republic,Bharat,Hindustan, 245 646',
    description:
        "From the outside this house looks grandiose. It has been built with tan stones and has white brick decorations. Tall, rectangular windows add to the overall look of the house and have been added to the house in a very asymmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, five bedrooms, a modest dining area, an office and a modest garage.The building is shaped like a short U. The two extensions are linked by a patio.The second floor is smaller than the first, which allowed for a roof garden on one side of the house. This floor has roughly the same style as the floor below.The roof is low and rounded and is covered with black roof tiles. One small chimney pokes out the center of the roof. A few round, small windows let in enough light to the rooms below the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4',
    totalReviewed: '6633',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topCheapestHotelList_4',
    mainImage: "hotel_5.jpg",
    name: 'Seacoast Hotel',
    price: '36',
    city: 'Kenya, Nairobi',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks gorgeous. It has been built with spruce wood and has tan stone decorations. Tall, rectangular windows brighten up the house and have been added to the house in a very symmetric way.The house is equipped with an average kitchen and three bathrooms, it also has a snug living room, four bedrooms, a cozy dining room, a multimedia room and a large storage room.The building is fairly rounded in shape. The house is half surrounded by a covered patio.The second floor is the same size as the first, which has been built exactly on top of the floor below it. This floor follows the same style as the floor below.The roof is low and triangular and is covered with brown ceramic tiles. One small chimney sits at the side of the house. Several long, thin windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '3.9',
    totalReviewed: '6969',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topCheapestHotelList_5',
    mainImage: "hotel_6.jpg",
    name: 'Crimson Jewel Hotel',
    price: '86',
    city: 'Japan, Tokyo',
    address: '4467 Homenick Stravenue, Janesville, USA, 25295-4823',
    description:
        "From the outside this house looks very elegant. It has been built with white pine wood and has spruce wooden decorations. Tall, squared windows brighten up the house and have been added to the house in a very asymmetric way.The house is equipped with a large kitchen and one modern bathroom, it also has a cozy living room, three bedrooms, a small dining room and a spacious basement.The building is rectangular shaped. The house is half surrounded by overgrown wooden overhanging panels.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a very different style than the floor below.The roof is low and slanted to one side and is covered with brown roof tiles. One small chimney pokes out the center of the roof. There are no windows on the roof.The house itself is surrounded by a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers.",
    ratings: '4.8',
    totalReviewed: '8856',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topCheapestHotelList_6',
    mainImage: "hotel_7.jpg",
    name: 'Crimson Jewel Hotel',
    price: '23',
    city: 'Canada, Ottawa',
    address: '24615 Mayra Trail, Lake Carolyneside, USA, 40585',
    description:
        "From the outside this house looks very elegant. It has been built with red pine wood and has sandstone decorations. Tall, squared windows let in plenty of light and have been added to the house in a very symmetric way.The house is equipped with a huge kitchen and one modern bathroom, it also has a generous living room, five bedrooms, a modest dining area, a playroom and a modest garage.The building is rectangular shaped. The house is fully surrounded by cloth sunscreens.The second floor is smaller than the first, which, in combination with its placement, creates an original look. This floor has roughly the same style as the floor below.The roof is low and triangular and is covered with overlapping roof tiles. Two small chimneys poke out the center of the roof. Large, skylight windows let in plenty of light to the rooms below the roof.The house itself is surrounded by a well kept garden. Grass, flower patches and trees have been placed in a stylish way.",
    ratings: '4.8',
    totalReviewed: '1256',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  ),
  HotelModel(
    id: 'topCheapestHotelList_7',
    mainImage: "hotel_8.jpg",
    name: 'Secret Court Hotel',
    price: '29',
    city: 'China, Beijing',
    address:
        '03324 Ganaka Inlet, Jhahaven, India,Indian Republic,Bharat,Hindustan, 199 862',
    description:
        "From the outside this house looks magnificent. It has been built with walnut wood and has grey brick decorations. Large, octagon windows add to the overall style of the house and have been added to the house in a very symmetric way.The house is equipped with a large kitchen and two bathrooms, it also has a small living room, three bedrooms, a roomy dining room, a library and a large basement.The building is shaped like a squared S. The two extensions extend into glass overhanging panels circling around half the house.The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.The roof is high and slanted to one side and is covered with grey roof tiles. Two large chimneys sit at the side of the house. There are no windows on the roof.The house itself is surrounded by a modest garden, covered mostly in grass, a few flower patches and with a small pond.",
    ratings: '4.5',
    totalReviewed: '1265',
    ratingList: ratingList,
    facilities: hotelFacilities,
    details: hotelDetails,
    galleryPhotos: galleryPhotos,
  )
];
